### ISSUE TITLE
NERSC workflow plan

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#116]
The following came up in the SSim meeting:

@cwwalter - Max wall clock (?) time per job is 36 hours, potentially an issue.

@danielsf It looks like they only allow users to have 200 jobs in the queue at once.
Here's [the list of policies (for their 'Cori' machine)](http://www.nersc.gov/users/computational-systems/cori/running-jobs/queues-and-policies/) that I have been working from.

Are there other things we should watch out for when getting set up to run at NERSC?

**Comment by linan7788626** [comment]
Hi @drphilmarshall  @danielsf 

If "200 jobs" is a limit of running phosim on Cori, maybe we could use mpi4py to run these jobs in embarrassingly parallel. It is considered as one job only. Here are an example code and an submission script. I have used such method running 1000 jobs once, and there is no problem. I hope this would be helpful. 

```python
import numpy as np
import subprocess as sp
import sys
import os

def test_run(ind):
	PHOSIMPATH="/global/project/projectdirs/hacc/nanli/phosim_cori/phosim-phosim_release-ea7a58e8b744"
	if os.path.exists("../workdir/"+str(ind)):
		pass
	else :
		sp.call("mkdir -p ../workdir/"+str(ind),shell=True)

	if os.path.exists("../outdir/"+str(ind)):
		pass
	else :
		sp.call("mkdir -p ../outdir/"+str(ind),shell=True)
	op_frames = "../amazeball_frames/amazeball_frame_"+str(ind)+".txt"
	cmd = " ".join(("python",PHOSIMPATH+"/phosim.py",op_frames,"-o","../outdir/"+str(ind), "-w","../workdir/"+str(ind),"-c", PHOSIMPATH+"/examples/nobackground"))
	sp.call(cmd,shell=True)

if __name__ == '__main__':
	from mpi4py import MPI
	comm = MPI.COMM_WORLD
	size = comm.Get_size()
	rank = comm.Get_rank()

	num_imgs = int(sys.argv[1])

	for i in xrange(rank,num_imgs,size):
		test_run(i)
```

```bash
#!/bin/bash -l
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J my_job
#SBATCH -e test.err
#SBATCH -o test.out

module load python
module load mpi4py

srun -n 1000 python-mpi ./batch_phosim_jobs_mpi4py.py 1000
```

**Comment by richardxdubois** [comment]
@djbard should comment, but is this 200 jobs limit just for the "serial" queue? I thought we were trying to find ways around that.

**Comment by tony-johnson** [comment]
I *think* Debbie told us that the type of jobs we would typically want to run are what NERSC calls "shared" (we don't necessarily want the whole machine for each job). The limits on these jobs are much less tight (500 jobs running per user, 2500 jobs submitted). In addition I think she indicated there may be some flexibility in those limits.

**Comment by djbard** [comment]
Hello:
 if your jobs are single-core, you should use the "shared" queue where you can run on only one core (or however many you require). You can indeed have 2500 jobs in this queue at any one time with 500 running. This is the recommended way to run single-core jobs, rather than bundling them up with mpi4py/taskfarmer or similar. Those methods do work, of course, but the whole point of the shared queue is to render those workarounds unnecessary. 
 Of potential interest: the "shared" partition (partition==queue in SLRUM-speak) accounts for 46% of all NERSC jobs so far this year, but only 1% of the run time. The average wait time in the shared partition is currently a couple of minutes - there are 40 nodes in Cori dedicated to this partition (i.e. not used for regular/debug partition jobs).

**Comment by djbard** [comment]
(btw please do @mention me if you have specific NERSC questions, I'm not following these issues closely :)

**Comment by cwwalter** [comment]
@djbard what about the case if you have a job that is going to run for 100 hours or something?  Is that not possible in the current queuing system?

**Comment by djbard** [comment]
@cwwalter nope, not possible. The max queue time is 48 hours for shared/regular. You'd want to checkpoint/restart in that case - it's a fairly common case for NERSC users.

**Comment by djbard** [comment]
@cwwalter did you have something specific in mind?

**Comment by cwwalter** [comment]
Well... I think that some of Tony's tests were already 45 hours.  And we have a lot of effects turned off.
1 Chip is the minimum phosim unit.  So I assume when everything is turned on and the sky is more realistic we might very well pass that time.

Personally, I also have phosim sensor jobs were I am trying to run flats that can run for ~ 2 weeks.

I'm not sure if PhoSim can do that sort of checkpointing...

**Comment by cwwalter** [comment]
@djbard Forgot to mention you in my answer. + is the checkpointing something built in on cori?  I mean is it like condor where in principle if you link things properly the queuing system can do the checkpointing for you?

Or are you responsible yourself?

**Comment by djbard** [comment]
Checkpointing is not built in to Cori, a la condor. You need to have checkpointing built into your application. Slurm does have a checkpoint option, but I haven't used it myself (nor has anyone in my immediate vicinity) so I can't vouch for it. 
http://slurm.schedmd.com/checkpoint_blcr.html

**Comment by djbard** [comment]
I also don't know about PhoSim's checkpointing - but I'm 99% sure it's integrated with Condor and is not standalone. This has always been a barrier to running phosim on non-condor clusters/machines.

**Comment by cwwalter** [comment]
@djbard No that's not right...

PhoSim can be run alone.  There is part of the script that knows about condor.  It frames out each chip to one job in a cluster.  But there is no reason that can't be adapted to any batch system.  Condor makes this sort of thing easy so it might be more work for SLURM or something but there is nothing magical about it.

I just can't remember about checkpointing.  Since it can run on OSG where jobs are often short it may be set up.  We should ask @johnrpeterson.  I think it exists at some level but I don't know if it can restart just the raytracing part for example.

**Comment by cwwalter** [comment]
Oh I misread what you typed.  You are saying that the checkpointing itself is using the condor mechanism.  That's possible.  I'm not sure we have to ask John.  But, I sort of doubt it.  The reason is that it only works in the standard universe where you have a single executable linked with the libraries.  The driver script would not work with this and there is no option I remember for having the executables linked that way.

I could be wrong though.  If John doesn't answer I'll take a look.

**Comment by cwwalter** [comment]
So, more generally for really long running jobs we have to write our own checkpointing.... that's too bad.  Can I ask how this works in practice in the queuing system?  

Let's say I have a job that needs to run for 2 weeks and I make it know how to checkpoint.  I guess SLURM sends it a signal that says "I am about to kill you".  So, I save my state.

What happens then?  Do I go back to the end of the queue and have to wait another several hours etc to restart?  Or, once jobs have started and are "running" do they have some sort of priority to finish?

**Comment by cwwalter** [comment]
BTW, it's hard to find good documentation on how to use it or how it works but from poking around it looks like BLCR (that Debbie referenced )is powerful. It relies on a Linux kernel module to save the state.

**Comment by djbard** [comment]
@cwwalter in the queue system, you can link together jobs as "dependencies", so you can have one job run, output checkpoint files, and the next job in the chain can pick up those files when it starts running. It will depend on how busy the batch system is, and the configuration of how "priority" is defined (this is constantly being tweaked to ensure jobs run fairly across the board) but you would not start from the back of the queue - the dependent job would probably start quickly. Of course, if you don't know how long your job will take, you don't know how many dependent jobs to submit, but that's another problem :) And since PhoSim is single core, you would be using the shared partition which has very high throughput/wait times. 
And yes, I did mean that PhoSim checkpointing works only with Condor, for example when we talked about running PhoSim at SLAC the same issue came up. But I'm not the expert here :)

**Comment by johnrpeterson** [comment]
Debbie-

I would say, in general, if possible, it is always better to use phosim via CONDOR.  CONDOR is the defacto standard for high throughput computing (HTC) (which phosim is an ideal application of).  Condor has its own checkpointing mechanism that will save the current state frequently and that has worked well in the past.  Condor is useful for other reasons in that we have platform-independent scripts that we have optimized the amount of I/O per job over years of experience, so you can have efficient throughput computing.  In addition, the whole thing with phosim is packaged very nicely so you can be doing something on your laptop with phosim and do the exact same thing on massive computing and only change the “-g condor” option.  So you don’t have to worry about diverging anything because there is no “porting” process.

So in general if you are able to install condor on your system then you should.  I also can help out connecting you to ways of running on either the OSG or the Diagrid.  Everyone should be able to connect to that and there are institutions supporting LSST as a virtual organization (VO) on those grids resulting in lots of HTC CPU hours.    Please let me know if you are interested in this, because this has been very helpful in project data challenges, and is the way we are doing most phosim runs.

Another point—   From past experience often we have found that a significant number of apparently long-running phosim jobs actually are not due to phosim, and just are usually due to idiosyncracies of the system (networking? memory allocation?), because they are not repeatable.    But, for sure, some long jobs are when phosim has a particularly bright star or a lot of full moon background.  You can run a fraction of light in sequence with phosim and therefore set up your own effective checkpointing.  This will then, however, reduce your throughput drastically because it removes the parallelism.  I see this more as a method if you have a particularly long job you want to run by hand.

In addition, in less than a year, roughly, we will release a fully multi-threaded phosim for use on multi-core systems, which will make much of this discussion irrelevant.

john



On Feb 11, 2016, at 8:51 PM, djbard <notifications@github.com<mailto:notifications@github.com>> wrote:


@cwwalter<https://github.com/cwwalter> in the queue system, you can link together jobs as "dependencies", so you can have one job run, output checkpoint files, and the next job in the chain can pick up those files when it starts running. It will depend on how busy the batch system is, and the configuration of how "priority" is defined (this is constantly being tweaked to ensure jobs run fairly across the board) but you would not start from the back of the queue - the dependent job would probably start quickly. Of course, if you don't know how long your job will take, you don't know how many dependent jobs to submit, but that's another problem :) And since PhoSim is single core, you would be using the shared partition which has very high throughput/wait times.
And yes, I did mean that PhoSim checkpointing works only with Condor, for example when we talked about running PhoSim at SLAC the same issue came up. But I'm not the expert here :)

**Comment by djbard** [comment]
@johnrpeterson: I'm excited to hear there's a full multi-threaded version in the works! That's great news, I look forward to seeing how that scales. 
 As you know, we don't have Condor installed at NERSC - we use Slurm as our workload manager and we don't support Condor. It would be nice to be able to run PhoSim efficiently without Condor but I understand it's been optimised for Condor. 
BTW, NERSC used to be an OSG site (but their allocation was not renewed by the DoE this year). Perhaps there's some way of using that interface?

**Comment by johnrpeterson** [comment]
On Feb 16, 2016, at 4:51 PM, djbard <notifications@github.com<mailto:notifications@github.com>> wrote:


@johnrpeterson<https://github.com/johnrpeterson>: I'm excited to hear there's a full multi-threaded version in the works! That's great news, I look forward to seeing how that scales.
As you know, we don't have Condor installed at NERSC - we use Slurm as our workload manager and we don't support Condor. It would be nice to be able to run PhoSim efficiently without Condor but I understand it's been optimised for Condor.
BTW, NERSC used to be an OSG site (but their allocation was not renewed by the DoE this year). Perhaps there's some way of using that interface?

yeah, probably if you go to the point of entry and then just submit a condor job (i.e.  phosim examples/star -c examples/nobackground -g condor) and see what happens.

**Comment by cwwalter** [comment]
I wanted to recreate some relatively complicated condor cluster semantics using SLURM for PhoSim jobs at NERSC.  I managed to do it using the "array" mechanism.  Somethings about this are better, somethings worse than my condor solution but it is quite flexible.  This approach allows you to submit a large group of jobs as a cluster and depending on the cluster entry number choose different options.  Take a look here:

https://github.com/cwwalter/brighter-fatter/blob/master/slurm_spot.sh

if you are interested.

The things to pay attention to:

#SBATCH --array=1-21,101-121

tells you there should be 42 jobs in this array they are numbered 1-21 and then 101-121

# Output
#SBATCH --output=logs/spot-%a.log
#SBATCH --error=logs/spot-%a.log

the output log files are labeled with the job number (%a)

```
case $((SLURM_ARRAY_TASK_ID/100)) in
    0) COMMAND_FILE=perfect_seeing ;;
    1) COMMAND_FILE=dev_charge_sharing ;;
    *)
	echo "Command File not defined!"
	exit
esac

# Set the source file depending on the array number (lowest two digits)
SOURCE_DIR=sources

case $((SLURM_ARRAY_TASK_ID%100)) in
    1) SOURCE_FILE=1000e ;; 
    2) SOURCE_FILE=2000e ;;
```
Use the $SLURM_ARRAY_TASK_ID to decide what to do for each entry.  Here I want to set two things separately (both the command and source file) so I am using "mod" to distinguish the 100s digit for the command file and the remaining number for the source file.

Just in case anyone else found this useful.  If you wanted to make a slurm grid option for condor using the array option is probably the way to go.  You could assign a chip/entry.  Then, like in condor you can control this set of jobs together.

**Comment by tony-johnson** [comment]
More recent discussion has been taking place here:

https://docs.google.com/document/d/1NnsW3XZTQcJNqVi-3RZQivCqSMlY753S2MZk9dsbMNg/edit?usp=sharing
