### ISSUE TITLE
Check that 1 visit per filter per night for 1 season makes sense for Run 1

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#118]
We decided in our meeting (#111) that we'd try for 1 visit per filter per night, and 1 complete season (starting on c. MJD 60150 or so). @rbiswas4 is going to check this out. Rahul, can you also please update the Run 1 plan markdown file, as in #110? Thanks!

**Comment by rbiswas4** [comment]
I put a proposal  in https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/SN_sims/Kraken_vistsSelection.ipynb, and have briefly discussed with Simon. The notebook has some details of the numbers behind the proposal, but for your convenience: 

Proposal :
1. We want to select all the unique night and band combinations in the 10 years of Kraken. As we have seen above this is 1680 visits.
2. We will give the phosim instance catalogs and seds for running phosim on the cluster, and we should run these in order of expMJD or night. If we run out of compute time at a 1000, then we will have a little more than half of the survey
3. When we get more (phoSim) simulation time, we can finish the 10 years. If we have more time than than, I suggest we fill in other observations in the 2nd year as shown in the above figure around 60300. This is another 500 observations. After than we can fill in the rest of the second year and then other years. **The priority for the the second year (and could have been elsewhere) is because I can make sure that there a few supernovae that are at high redshift and 'visible' at that time.** I need to know this ahead of time, and that is why I putting this out now. 

You can take a look at the two csv files : 
- : has all the OpSim columns corresponding to the selected visits https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/SN_sims/SelectedKrakenVisits.csv
- Only the obsHistIDs (unfortunately, there is a second column which is a repeat of the same thing, I will fix that in a subsequent modification) https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/SN_sims/FirstSet_obsHistIDs.csv

**Comment by drphilmarshall** [comment]
Hmm - in #121 I commented thusly:

> From your plots I make it that season 2 runs from about MJD60190 to MJD60330, and so lasts about 140 days, or about 4.6 months. Good! In that period there are 45 nights with at least one visit, and it looks like about 21 of them have all 5 of the grizy filters, while the other 24 nights are spent hammering away at the u-band. If we just keep one visit per filter per night, the total number of visit images looks like being about 21x5 + 24 = 129 or so. This is pretty small compared to Tom's 1000 per week capacity: but maybe still big enough to get some nice light curves and analyze them? @wmwv ?
> 
> The night-to-night cadence in this DDF looks like being 140/(21+24) = 3 days, so I guess yes, these light curves will be nice! (Just not very deep.) Thanks you two!

I see now that I misunderstood your proposal: you're suggesting we do the whole 10 years rather than just season 2. That's fine with me - as you say, its moe than 1000 images but not much more. And TBH, if we only have time to do a few seasons that would be fine, I think.

**Comment by rbiswas4** [comment]
> you're suggesting we do the whole 10 years rather than just season 2. 
Yes, that is 1680 images. If we can only get 1000, that is fine. But we can keep adding simulations later.

**Comment by drphilmarshall** [comment]
Agreed - I like the extensibility of attempting 10 years but only *needing*
a fraction of it. I think this plan will give a good set of light curves to
look at in March, provided the input SNe are bright enough. Each point on
the light curve will come from a single visit with ~24th mag depth - so to
make sure we get light curves with enough S/N, do we need to bring down the
high end of the redshift range? Would a z=0.8 SN be well-measured in these
Run 1 light curves? If not, might we want to focus on a more nearby subset
in Run 1? What do you think, Rahul? It would be frustrating not to see the
supernovae we put in...

**Comment by rbiswas4** [comment]
I can give a better answer later today to some of this, but it would be good to ask what tests you have in mind. What are the points of failure if we do not have high SNR points in the light curve? Detection is a single image process so having any other images will not help, correct?

My impression is that we should try to ensure have enough low z SN for some tests, but having high z SN (even if we don't find them) is useful.

**Comment by SimonKrughoff** [comment]
@drphilmarshall The reason Rahul did what he did was ensure we would have 100 5sigma supernova detections per visit.  Then on the phonecon yesterday, it was asked that we only have 100 supernovae per season.  I would much prefer to go with the former since it guarantees we'll have detections to work with (and we know what we are getting).  Is there really a strong reason to change?

**Comment by drphilmarshall** [comment]
Only that you SN people can do much more interesting tests if you have a
well-measured light curve than a single epoch detection. Don't you want the
peak magnitude of at least some systems to be very high S/N? Maybe this
will fall out naturally from your nice flattish redshift distribution (ie
the low z ones will have good light curves) so perhaps I'm worrying over
nothing.

**Comment by SimonKrughoff** [comment]
O.K.  I see.  Thanks for the clarification.  I think @rbiswas4 may have had a few plots of the S/N distribution per visit.  I'll have a look.

**Comment by drphilmarshall** [comment]
Hi @SimonKrughoff - Rahul seems OK with the instance catalogs that he and Bryce are making, so I guess we can close this one, maybe? Did you find any good plots? I ask you because Rahul is busy furiously transferring files to us :-)

BTW this issue is a dupe of #131 in some sense, which is good news for whoever signs off on the Run 1 supernovae (as they'll get to close two issues at once! :-).

**Comment by rbiswas4** [comment]
Added the notebook as @SimonKrughoff wanted to point to the table in output 50 of  https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/SN_sims/Twinkles_SimulatedSN_Setup.ipynb

This is showing how the initial flat distribution needs to be bumped up in each z bin to  get an estimate of 100 5 sigma SN detected per image.
