### ISSUE TITLE
Twinkles Session at the SLAC Collaboration Meeting

### ISSUE THREAD

**Issue by KirkGilmore** [DarkEnergyScienceCollaboration/Twinkles#150]
Hi all! Looking forward to hearing more about Twinkles at the collaboration meeting next week. What's the plan for the [Twinkles task force session](https://confluence.slac.stanford.edu/display/LSSTDESC/Twinkles+I+data+challenge)?

**Comment by drphilmarshall** [comment]
Good question. We're in sprint mode right now, but our goal is to have Run
1 data products and some very early validation analysis done and ready for
digestion, so we'll want to spend time on that. I guess we'll also need an
overview for new and interested people :-) And also discussion time, since
we need to make an initial plan for how we get from Run 1 to Twinkles 1
(the main data generation run is due to be finished by the early fall, and
we have the Oxford meeting in between).

Twinklers: what do you think about the following top-of-the-head session
agenda?

* Twinkles Overview and Run 1 Plan - @drphilmarshall and @wmwv
* Run 1: CatSim/OpSim/Sprinkler inputs - @rbiswas4 and @jbkalmbach
* Run 1: PhoSim Simulation Workflow results - @Simon Krughoff and
@TomGlanzman
* Run 1: DM Level 2 Processing Workflow results - @Simon Krughoff and
@tony-johnson
* Run 1: Image and Forced Photometry Analysis - Open Mic (but with
contributed slides!)
* Discussion:
  * Twinkles as a CI Pathfinder: How well did we do in Run 1?
  * Beyond Run1: Twinkles 1 feature requests (science and infrastructure)
  * Timeline to the Twinkles 1 Data Release

We have 90 minutes on Weds at 11am, in a 28-person meeting room. We're on
at the same time as WL2, LSS1, and CL1, so we may not get a big crowd.

I'll make a Google slide set for us all to contribute to once we settle on
a plan!

**Comment by cdfassnacht** [comment]
I may be able to join this session remotely if you have the ability for
off-site people to connect in the room that you will be using.

   Chris

On Fri, Feb 26, 2016 at 5:46 PM, Phil Marshall <notifications@github.com>
wrote:

> Good question. We're in sprint mode right now, but our goal is to have Run
> 1 data products and some very early validation analysis done and ready for
> digestion, so we'll want to spend time on that. I guess we'll also need an
> overview for new and interested people :-) And also discussion time, since
> we need to make an initial plan for how we get from Run 1 to Twinkles 1
> (the main data generation run is due to be finished by the early fall, and
> we have the Oxford meeting in between).
>
> Twinklers: what do you think about the following top-of-the-head session
> agenda?
>
> * Twinkles Overview and Run 1 Plan - @drphilmarshall and @wmwv
> * Run 1: CatSim/OpSim/Sprinkler inputs - @rbiswas4 and @jbkalmbach
> * Run 1: PhoSim Simulation Workflow results - @Simon Krughoff and
> @TomGlanzman
> * Run 1: DM Level 2 Processing Workflow results - @Simon Krughoff and
> @tony-johnson
> * Run 1: Image and Forced Photometry Analysis - Open Mic (but with
> contributed slides!)
> * Discussion:
> * Twinkles as a CI Pathfinder: How well did we do in Run 1?
> * Beyond Run1: Twinkles 1 feature requests (science and infrastructure)
> * Timeline to the Twinkles 1 Data Release
>
> We have 90 minutes on Weds at 11am, in a 28-person meeting room. We're on
> at the same time as WL2, LSS1, and CL1, so we may not get a big crowd.
>
> I'll make a Google slide set for us all to contribute to once we settle on
> a plan!
>
>
> On Fri, Feb 26, 2016 at 5:18 PM, Kirk Gilmore <notifications@github.com>
> wrote:
>
> > Hi all! Looking forward to hearing more about Twinkles at the
> > collaboration meeting next week. What's the plan for the Twinkles task
> > force session
> > <
> https://confluence.slac.stanford.edu/display/LSSTDESC/Twinkles+I+data+challenge
> >
> > ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/150>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/150#issuecomment-189551750>
> .
>



-- 
Chris Fassnacht
Professor, Physics Dept.
UC Davis
1 Shields Ave.
Davis, CA 95616
+1-530-554-2600

**Comment by drphilmarshall** [comment]
We certainly will have Blue Jeans open to all-comers - thanks for making time, Chris!

All:  I take it you are all fine with making Twinkles slides for a common set. I suggest we build off the update we already gave a few weeks ago, and add more information about the reality of Run 1. Here's the [Google slideset for you to edit](https://docs.google.com/presentation/d/1MdGGDrITW4-n04goJNYBAoVwnQBjRkibxuJY8EJZWXc/edit?usp=sharing)  Its pretty structured to start with, and Ive left blank slides with names on to be filled in. The "validation analysis" section at the end is there for you to add slides for your plots and code. Open season! :-)
