### ISSUE TITLE
Cannot download images

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#153]
Reposting for @DominiqueFouchez:

> How do I download an image ? 
> When I try the download link, a jnlp file is proposed and not handled by my browser (firefox on linux).
> When I try the download on the SLAC location :
> `/nfs/farm/g/desc/u1/Pipeline-tasks/Twinkles-phoSim/phosim_output/000000/output/lsst_a_484933_f4_R22_S11_C00_E000.fits.gz`
> I got error :HTTP Status 500 - /nfs/farm/g/desc/u1/Pipeline-tasks/Twinkles-phoSim/phosim_output/000000/output/lsst_a_484933_f4_R22_S11_C00_E000.fits.gz (No such file or directory) 

@jchiang87 which is the actual data download link? You mentioned its existence to me the other day...

PS. Relevance to #148

**Comment by jchiang87** [comment]
Unfortunately, the file Dominque was trying to access was moved, presumably because it was created with the truncated instance catalog Tom used for his tests.  The other folders, e.g., 

http://srs.slac.stanford.edu/DataCatalog/?folder=14635892

and 

http://srs.slac.stanford.edu/DataCatalog/?dataset=14635929

At the latter page, it will work if you click at the full path under `Location` at the bottom (i.e., ignore any links labeled `Download` unless you want to use the java-based Download manager.)

**Comment by drphilmarshall** [comment]
Thanks Jim!

**Comment by johnrpeterson** [comment]
Dear Twinkles Team-

There are some tickets that have been generated for PhoSim in running this in the pilot projects.  That is great!

One small change that would help me to help you more would be if you could please indicate in your ticket (or through private email to myself) whether you feel it is fine if the problem is addressed in the next major release (which we label phosim vX.Y) or you need a fix soon in a patch (which we label phosim vX.Y.Z).  The difference being that the timescale for the former is many months, whereas the latter could be days.  

Historically, I have limited the patches (we have done about two dozen) we have done to absolutely critical errors (i.e. a seg fault that is not even due to a error by the user), but it doesn’t have to be that way.  In some cases, there are not quick fixes, but anyways please let me know as it is hard for me to tell by the typical exposition in a ticket whether the problem is holding someone up or just something that you have found and would like addressed in the future.

Thanks,

John
