### ISSUE TITLE
Retreat location

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#181]
I've taken an action to help organize the location of a Twinkles retreat.  Since I know it better, I thought about Seattle first.  Options here are:
1. [Friday Harbor](http://depts.washington.edu/fhl/) -- **Pros:** Secluded, picturesque **Cons:** expensive?, hard to book, somewhat hard to get to.
2. [Talaris](http://www.talarisconferencecenter.com/) -- **Pros:** Easy to get to, close to campus **Cons:** expensive?, close to campus.
3. Someplace east of the Cascades [e.g.](http://www.redlion.com/wenatchee) -- **Pros:** Might be very inexpensive if not in ski season, picturesque, secluded **Cons:** May be tricky to get to.
4. Campus -- **Pros:** Easy to book, easy to get to, inexpensive meeting space **Cons:** Could be distracting, hotels are expensive.

**Comment by drphilmarshall** [comment]
Thanks Simon, these are good to options to have in mind. By the end of
Friday lunchtime I think we were leaning towards doing something down here,
though - just because the SLAC LSST Science budget is stretched pretty
thinly. For me, the big question is whether we could make a week's retreat
residential for all, or if we instead need to make it within driving
distance of the SLAC team's homes. With some commitment on our part, I
think the latter could work - and I could look into nearby venues. There's
also SLAC itself, but that would require greater effort on our part to
clear our schedules fully in order to work intensively on Twinkles with you.

**Comment by drphilmarshall** [comment]
I'll put this on the agenda for tomorrow, but I wonder: how does Half Moon Bay as a retreat location sound to you?

**Comment by SimonKrughoff** [comment]
Sorry, I dropped this.  Half Moon Bay sounds good.  I don't know about any of the conference resources there, but I can look into it.

**Comment by KirkGilmore** [comment]
There is a great resort right on the beach just south of HMB.
Ritz- Carlton.  May be a bit pricey but it's spectacular.

kg

From KG's BB

-----Original Message-----

**Comment by drphilmarshall** [comment]
I'm thinking we'll need 1) cheap accommodation for the UW/Pitt crowd (like
an airbnb house) and 2) a meeting room with good wireless. Whiteboards and
projectors we can improvise. Shoestrings will be supplied.

**Comment by drphilmarshall** [comment]
I found us a nice house on the coastside: 5 BR, sleeps 10, high speed internet and a home theater for data visualization. [What do you think?](https://www.vrbo.com/413894) The SLAC team could commute to HMB pretty easily, and the UW/Pitt crowd could all (I think) stay in the house, which for 6 nights would run to just about our whole $4k budget. All you'd have to do is get to SFO, and we should be able to figure out the local transport and grocery shopping from there.

**Comment by drphilmarshall** [comment]
OK, I never got any feedback about the house I posted, and it is no longer available: lesson is to book as early as possible! We have some options still. From the [doodle poll](http://doodle.com/poll/xpdcrkdzhaverii2), I think we are looking at 5 1/2 people staying residentially: @jbkalmbach @SimonKrughoff @danielsf @rbiswas4 @cmccully @wmwv . Given that Curtis is only following along in the background, and Michael will only join for part of the week, I think a 5BR house should be sufficient.

I recommend this one, in Montara: https://www.vrbo.com/326753
It's under $600 per night, about $3700 total (about $123 per person per night). I started an enquiry about a Sunday-Saturday rental, so that we can start early on Monday and hang out through Friday. Let me know what you think!

**Comment by drphilmarshall** [comment]
We settled on spending our travel money on going to Pittsburgh in November rather than the Pacific coast in October. Hooray! I will release the house we had planned to book and help any Twinkles TF member who emails me about travel support get paid.
