### ISSUE TITLE
Add in remaining TDC1 rung 4 lenses.

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#192]
In #117 we decided to sprinkle in a set of lenses defined by the TDC1 rung 4, but for run 1 we settled on only sprinkling in the first 200 from that rung. We need to update our sprinkling catalog with the rest of rung 4 since only taking the first 200 left out all quads from the lens catalog.

**Comment by drphilmarshall** [comment]
No quads! Thanks for rectifying this sorry situation, Bryce.

**Comment by drphilmarshall** [comment]
Hmm - while putting together this week's meeting agenda it occurs to me that this issue is worth discussing with the group. Fixing the lens sample to include quads is something we could test in Run 2 - *if* we decide to re-make the images as well as re-do the L2 processing... I'll put this question to the floor tomorrow.
