### ISSUE TITLE
Install shared Stack at NERSC

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#204]
@djbard @heather999   Any suggestions on where this Stack should be installed?

**Comment by heather999** [comment]
@djbard has pointed us to: /global/project/projectdirs/lsst/lsstDM/Cori with the caveat that we might still want to consider how the directories should be organized.

But I'm also wondering what version of DMstack - a dev conda installation? and how will it be kept up to date with what folks want and need in terms of various modules. Do we want to set up a stable version being used for work (which I gather will technically be a dev version of some DM packages) and a test (dev) version for evaluation before it is used for real runs? I could imagine using conda environments for this...  I fully expect you have some opinions based on your experience of using DMstack with Twinkles @jchiang87?

**Comment by jchiang87** [comment]
I don't know what people will want regarding "stable" vs "development" version of the Stack and am inclined not to think about it very deeply unless forced.   Twinkles may need a ticket branch of obs_lsstSim, and maybe some sims packages for the sprinkler to work.    If we can build those particular packages against a "dev" conda install of the Stack+lsst_sims, then that's what we'll need for  Twinkles.  Others can build their special cases against that Stack themselves.

**Comment by rbiswas4** [comment]
Jim I put my suggestion in the google doc.

**Comment by heather999** [comment]
Just for posterity, @rbiswas4, here is what you wrote in the google doc:
The lsst project space is located here /project/projectdirs/m1727/ . In previous attempts on edison, project/projectdirs/m1727/edison/loadmodules.sh was useful (but what we had used was a conda build)

**Comment by danielsf** [comment]
Regarding the status of DM conda installs:

Currently, there are no builds of the DM stack in the conda dev channel.  The only available conda install of the DM stack is v11.0, available in the 'stable' conda channel.  v11.0 dates back to Summer 2015, and is probably too old for our purposes.

Now that it has been decided that we are going to publish copies of the DM stack tagged as 'sims' (tagged weekly releases of the DM stack against which the releases of the sims stack can self-consistently be built), I will try to release dev conda builds of the DM stack the whenever I update the dev conda build of the sims stack (that should happen by the end of the week, but I've been saying that for two weeks now).  I do not promise that the conda build of the sims-tagged DM stack will work.  I will post here after I have made the attempt.

**Comment by cwwalter** [comment]
I thought the project space was 


/global/project/projectdirs/lsst


?

Is that not right?

**Comment by rbiswas4** [comment]
Thanks @heather999 !

To clarify what a few of my previous statements (others who might know more about that could chime in):
- The 'suggestion' for location was based on what I thought we all had write/read access to (m1747 is an allocation with PI Peter Nugent), rather than put it in any one of our home directories, where it will count against the individual quota and we will have to set up permissions by hand. If there is another location with these properties (like the lsst space being suggested, that is great, we could have the shared stack there too!) 

I had installed a conda build of the stack on edison, but during the DESC meeting the build was found to be too old to be currently useful, and as @danielsf points out, we don't have the next build. Because of this, I had kind of assumed during the meeting that @jchiang87 wanted to use eups distrib install

- In the past some people @wmwv , @SimonKrughoff and myself have tried building the DM and SIMs  stack on different NERSC machines with varying levels of success using the normal eups distrib install tool. Last summer, we could get a compiled version on edison but running it ran into problems. The choice of modules that I used  in the /project/projectdirs/m1727/edison/loadmodules.sh file (like @heather999  said above). An advantage of this approach was that we could work with the anaconda python provided by NERSC rather than installing it ourselves. It was not hard to install anaconda as part of the stack, but it was hard to ensure that the all stack components were built using that anaconda python. 
- This is when we talked about using conda binaries, and the conda binaries installed were successful, I was able to use the sims stack (which depends on DM components and was not possible before).

**Comment by heather999** [comment]
While I have not played around with NERSC installation of the DMstack yet, I have dealt with that elsewhere. We might want to have our own Anaconda python installation so we have more direct control over what versions of various modules are available (I'm thinking about numpy, matplotlib and scipy specifically). Most of the time, when doing an eups distrib install, I prefer to have my anaconda python installation separate from the stack itself rather than have the installation of DMstack do it for me, but that's just my personal preference. I don't know if that is useful or desirable for a shared stack at NERSC.

Do we want the install on edison or cori or both? Thinking back to @djbard's DESC meeting presentation, I got it in my head we might be targeting cori - however I am absolutely not an expert on edison versus cori :)

Maybe a first step is to do a conventional DMstack eups installation to see how it goes. It would be an opportunity to see if we're happy with the directory organization, play around with submitting jobs, and solidify what versions of the sims packages we need.. and then move to the conda installation as it begins to be kept up to date with what is needed for Twinkles? If I followed @danielsf and @rbiswas4 correctly, we can't go with the conda distribution quite yet.

**Comment by djbard** [comment]
You should be targeting installation on Cori above Edison, since Cori is
better configured for DESC-scale work.
Of course, Cori didn't exist 6 months ago so that's why people originally
installed code on Edison.

RE the project space: indeed, m1727 is the repo name, but it's also called
lsst (I actually have no idea how this works and if/how to change it). I
have been using /global/project/projectdirs/lsst since that appears to be
the "official" space.
 You should ask Peter Nugent/Richard Dubois about if/how to clarify the
repo names.

**Comment by richardxdubois** [comment]
I don't know where the 1 TB partition came from. We could think about using it for shared installs actually. Maybe Peter knows the origin of that partition (I don't seem to be able to @ him).

**Comment by jchiang87** [comment]
Hey @drphilmarshall!  Could you add @heather999 as a Twinkles contributor so that we can assign her this issue? :-)

**Comment by drphilmarshall** [comment]
Done!

**Comment by heather999** [comment]
I set off to do an install at NERSC on Cori.  Thanks to @rbiswas4 for pointing me to your previous work on this - particularly the loadmodules.sh used for edison.  Cori has a slightly different list of pre-loaded modules - I adjusted it as I thought best (a bit of a shot in the dark!), but I made sure to load the anaconda python 2.7 and gcc 4.9.3.  Was there any particular way you were able to arrive at the list used for the edison installation last summer? Perhaps @djbard might be able to make some suggestions.
I got to the point of running "eups distrip install lsst_apps -t sims" this morning.. it went fine until the 6th package :) mariadb, where it did not get beyond the configuration step, it is complaining about systemd:
-- checking for one of the modules 'libsystemd;libsystemd-daemon'
-- Performing Test HAVE_SYSTEMD
-- Performing Test HAVE_SYSTEMD - Failed
-- Looking for include files HAVE_SYSTEMD_SD_DAEMON_H
-- Looking for include files HAVE_SYSTEMD_SD_DAEMON_H - not found.
-- Looking for sd_listen_fds
-- Looking for sd_listen_fds - not found
-- Looking for sd_notify
-- Looking for sd_notify - not found
-- Looking for sd_notifyf
-- Looking for sd_notifyf - not found
CMake Error at cmake/systemd.cmake:70 (UNSET):
  Unknown CMake command "UNSET".
Call Stack (most recent call first):
  CMakeLists.txt:341 (CHECK_SYSTEMD)

-- Configuring incomplete, errors occurred!
+ exit -3
The full build.log is here: /project/projectdirs/lsst/lsstDM/Cori/LSST_STACK_2016-04-07/EupsBuildDir/Linux64/mariadbclient-10.1.11.lsst2/build.log
I'm poking around to see if I can figure out how to fix that.. but I'm quite open to suggestions! :)

**Comment by rbiswas4** [comment]
@heather999 : for me the set of modules on edison came about more by trying to build on stuff @SimonKrughoff and @wmwv had done on nersc machines and rambling across failures than with any clear insight, other than wanting to use a set of nersc provided compatible modules. And obviously, things will need modifications on cori as you are pointing out.

I ran into a problem with mariadb during stack install on a different machine yesterday :  
the was because it needs is an openssl library, so maybe see if such modules are available. I was pointed to the following tickets by @parejkoj:

https://jira.lsstcorp.org/browse/DM-5170
https://jira.lsstcorp.org/browse/DM-5595

**Comment by heather999** [comment]
Thanks for the response @rbiswas4 I'll play around with the modules and see if I can move forward. I'm thinking I should do a module swap PrgEnv-intel PrgEnv-gnu..  I'll give that a try and see if I can use "module show" to help me understand what some of these other preloaded modules are.

**Comment by heather999** [comment]
There is a conda-based installation now available at NERSC for shared use. For now, I am hoping others can give it a try so we can work out any issues that arise. 
The install is here:
/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15
The directory contains a simple setup script: setupVanillaStack.sh
We backed off an installation from source due to the availability of lsst-apps and lsst-sims via the conda dev channel.. this was far easier and is hopefully up to date enough for most. (insert applause for @danielsf and @mjuric here) Long discussion available here: https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/210

**Comment by wmwv** [comment]
@heather999 
Awesome!  Thank you.

What is the equivalent of `setupVanillaStack.sh` that is less chatty and doesn't change the PS1 prompt?  Right now I'm just resetting the PS1 prompt after sourcing `setupVanillaStack.sh`, and this isn't a big deal.

**Comment by mjuric** [comment]
@wmwv I haven't looked at the script, but my guess is that you're looking for: http://conda.pydata.org/docs/config.html#change-command-prompt-changeps1

**Comment by wmwv** [comment]
@mjuric Thanks for the suggestion.  Sadly, no joy:

```
[cori09 ~] cat .condarc
channels:
  - https://conda-test.lsst.codes/dev/
  - defaults

changeps1: False
[cori09 ~] echo "setting up to use vanilla LSST_STACK installation"
setting up to use vanilla LSST_STACK installation
[cori09 ~] export INST_DIR=/project/projectdirs/lsst/lsstDM/Cori/conda-env
[cori09 ~] export LSST_STACK_VERSION=2016-04-15
[cori09 ~] module load python/2.7-anaconda
[cori09 ~] source activate $INST_DIR/$LSST_STACK_VERSION/LSST_STACK
discarding /project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/bin from PATH
prepending /project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/bin to PATH
(LSST_STACK-2016-04-15)wmwv@cori09>
```

**Comment by heather999** [comment]
Sorry @wmvw, time for a long story :)
I was unhappy with the length of the prompt that conda set when activating the environment (it was longer than it is now), but I wanted to indicate the updated environment via the prompt as the default. I saw conda allows turning off the updated prompt entirely but was concerned some may prefer to retain the special conda prompt. They provide hooks into the activate and deactivate calls and I cheated and set PS1 there :) I can remove that so it won't be a further annoyance.
I'll also update the setupVanillaStack script to provide verbosity options as well as optionally setting the prompt. Of course, one doesn't have to use that script at all - it was just meant to be a convenience - but it could at least be more flexible.

**Comment by jchiang87** [comment]
Thanks @heather999.  I can run all of the Twinkles Level 2 pipeline tasks as well as the Twinkles unit tests with this installation, so I think this issue can be closed.

**Comment by heather999** [comment]
@wmwv Finally fixed the script.. there is now a "-v" option if one desires chattiness, otherwise the script is silent.  Additionally, I've fixed it so that the use of the .condarc setting "changeps1" behaves as it should.  I also left my finagling of the activate script to make the truncated updated prompt the default.  So, if you prefer no changes to your prompt, setting changeps1 true should work as you expect now.
I'll close this topic tomorrow since the installation itself is done.  If you run into any troubles with the set up though, please open a new issue.

**Comment by wmwv** [comment]
Very kind.  Thank you.
