### ISSUE TITLE
Documentation design, README clean-up

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#208]
Hi @heather999 

We now have an epic to work on, based on today's meeting: #207 

Thinking about the design of a "Getting Started" page: I know we need a guided tour of the issues, with links to filtered subsets and guidance of how to parse the growing issue stack. But, we also need an introduction to the Twinkles code base - and this seems more like a job for `sphinx` (plus we should learn and teach how to document code this way). I think the issues tour has to be separate from the code base introduction - so should we make a "Getting Started" markdown file and link to the code docs from there? Perhaps with some high level explanation of what the code is for? 

It'd be good to clean up the README too - any suggestions? 

Thanks! :-)

**Comment by heather999** [comment]
Your suggestions sound perfectly reasonable and my inclination is to make a simple draft "Getting Started" page and iterate from there @drphilmarshall. 
First I need to better acquaint myself with what documentation is already available and perhaps the best people to poke when I run into questions: @jchiang87 @TomGlanzman and @sethdigel come to mind because I know them - but if there are others, please feel free to point me in their direction.

**Comment by drphilmarshall** [comment]
@KirkGilmore is our number 1 repo guinea pig right now - he's been trying
to figure out what we are up to, and will give us feedback at our next
meeting (next Thursday). So it's not that Kirk nows what we are doing and
what docs we already have - he can instead give us input as to how things
*should* be :-)

**Comment by heather999** [comment]
After @KirkGilmore's comments, I'd like to understand where GitHub markdown docs and Confluence fit together. So we have LSSTDESC: https://confluence.slac.stanford.edu/display/LSSTDESC/Twinkles (which points to GitHub), this GitHub area, and the more general DESC Computing area in Confluence: https://confluence.slac.stanford.edu/display/LSSTDESC/Computing+and+Infrastructure, is there anywhere else? For my part, I prefer to remain agnostic concerning Confluence versus GitHub/Markdown - it's just vitally important that we have a clear entry point to Twinkles and provide doc that can be easily kept up to date. Some potential contributors may be more likely to look in Confluence first - at the very least there needs to be a clear "This Way" sign to GitHub. There's also cross-over with the larger DESC effort, so some content is pertinent to a wider audience outside Twinkles and may exist in other places.

A random question: are there things that we wish to keep secure such as the BJ meeting info (which might belong in Confluence) rather than making them publicly available on GitHub?

As a side note, I just installed the ZenHub plugin - wow! That's more a comment to remind myself to make sure to include doc on how to get it installed. I'm assuming anyone accepted as a DESC repo member can use it?

I think I'll take a stab at playing with a draft README and/or Getting Started in Markdown and see where that takes me - it won't be complete, but at least we can use it as a starting point.

**Comment by tony-johnson** [comment]
A few personal comments to follow up on some of the remarks @KirkGilmore made.

I think it would be useful to have a page in confluence for the weekly Twinkles meeting, with essential information including bluejeans number. I think this would make it much easier to find rather than having to search github for a particular issue (we can always link to the github issue from confluence).  I would also like to see the weekly meetings (Twinkles and others) appear in the DESC confluence calendar (from where they automatically appear in my (google) calendar since I have subscribed to the DESC calendar:

**Comment by drphilmarshall** [comment]
@heather999 Thanks Heather - great if you can make a first attempt at a
Getting Started markdown page, and find a good way of linking to it from
the README and from confluence. We have another potential entry point as
well, in that we can make a very simple Twinkles website via the gh-pages
web hosting service. This would have the URL
http://darkenergysciencecollaboration.github.io/Twinkles and might be a
good place to point people to start. Interested to hear what you think -
I'm never quite sure what teh scope of a README shoudl be.

BTW if I google "Twinkles" we are nowhere to be seen, but "Twinkles LSST"
gets you straight to us:

[image: Inline image 1]

**Comment by drphilmarshall** [comment]
@tony-johnson  Good point, I should be posting the meetings to the
calendar. We can certainly make a weekly meetings page in confluence too
(or maybe just add notes about this from the current Twinkles confluence
page). I guess this confluence page serves as a introduction to the project
for DESC members who find it by browsing or searching confluence rather
than Googling for it.

Regarding the security of posting bluejeans room details and Google doc
links to Twinkles issues: I am still waiting for this to cause problems,
but have not been caught out yet! What's the worst case scenario? Do we pay
for BlueJeans calls by the minute? I don't think the Google doc history can
be erased by anyone except the page owner (and, knowing Google, I bet it
persists even after that).

**Comment by drphilmarshall** [comment]
Update: I moved the [Twinkles confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/Twinkles) to live under "Computing WGs" and added links to our meeting notes, and the BlueJeans room we always use. I also put our meetings on the DESC events calendar. The confluence page still points at the repo README as our entry point, for now.

**Comment by drphilmarshall** [comment]
Revisiting this issue: I think a clean-up of the README will suffice for helping people at the Tucson PCM get acquainted with our work.
