### ISSUE TITLE
Modify code to be runnable under Python 3

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#209]
The DM team are migrating to Python 3 this year and are in the process of converting their code to be runnable under Python 2.7 and 3.    See the discussions at [RFC-60](https://jira.lsstcorp.org/browse/RFC-60) and [here](https://dev.lsstcorp.org/trac/wiki/DM/Policy/Python3Prep).

We should follow suit and use the [future](http://python-future.org/quickstart.html) module and `futurize` script to make our code Python 3 compatible.

- [x] Run `futurize` on existing code.
- [x] Write tests to ensure new code is Python 3 compatible

**Comment by SimonKrughoff** [comment]
@jchiang87 Note that the official line is that LSST will be both 2.7 and 3.x compatible as of ~August.  There are some who think it would be easier/better to just take the leap and drop 2.7 compatibility, so that we can use Python3 features.  If you have an opinion (especially with a DESC perspective), I'd be very interested to know what it is.

**Comment by jchiang87** [comment]
My initial reaction is that people will be resistant to move directly to Python 3 and drop Python 2.7 since they will have code outside of their Stack usage and DESC that may/would also need to be migrated, but I may be wrong.  We should really run this by the WGs to get their reaction.

On the Camera side, I'm guessing that people using the Stack might be resistant for the same reason, but that contingent is still small and generally consists of "earlier adopters", so might be ok with dropping 2.7 sooner.  Also the Camera team will likely want to use only a "release" version of the stack, so if Winter2016 is still Python 2.7 compatible, a move by the DM team to full Python 3 usage right after that release might be ok.

**Comment by rbiswas4** [comment]
Since there is a small amount of code in Twinkles, it would perhaps make sense from the start that no code should be written that is incompatible with 3. ie. everything is written in a way compatible with 2.7 and 3.0. I am not sure if it is possible to write tests that will ensure this, given that Twinkles code will call sims/DM code which will not work with a python 3 version. Is it possible to have tests run in 2.7 and some kind of linter that checks that the usage is compatible with python 3?

**Comment by jchiang87** [comment]
@rbiswas4 Regarding Python 3 compatibility tests, I was thinking exactly as you suggest: run the usual tests with whatever Stack is available (presumably Python 2.7 flavored for some time), and have a linter check all the code for Python 3 compatibility.  Pylint seems to be up to the task.

**Comment by rbiswas4** [comment]
@jchiang87 I was worried that this kind of linter would be hard to setup. If pylint can do this, that is awesome. I think we should do this soon before we unintentionally land up with more of python 2.7 specific code.

**Comment by jchiang87** [comment]
@rbiswas4 [Here](https://travis-ci.org/DarkEnergyScienceCollaboration/Twinkles/builds/121062699) is a travis-ci build with `pylint --py3k` running on all of the `.py` files in the repo.  This looks like it does what we want.  The next step would be to `futurize` the current code.

**Comment by rbiswas4** [comment]
@jchiang87 Great!

So, if I understand correctly:
where we should have had a __future__ statement but don't, it says:
'missing' 
and where we have used a python 2 style print statement that is incompatible with python 3: it complains with print statement used.

A question:
- By default, I have a problem with pylint in that it seems to not recognize numpy modules as a valid members. Of course this, and other things can be switched off by configuration and we will have to do this if we put it in travis builds. I know this can be done a global  config for the user, but don't know if you can (are) do this locally within the repo. A local config is preferable, but I don't think a global one will have a real problem (potential of a conflict with usual config, but I doubt this is a real problem)

- I think you should push to master, commenting out the pylint line in .travis file, document the config you want us to use, and we should be able to check back all our code within a week having futurized it.
- in a [cheat sheet](http://python-future.org/compatible_idioms.html), a possible point of divergence is that there are multiple ways of achieving 2-3 compatibility. I don't think it makes sense to be picky (other than keep things that are said to have high overhead on python 2 out. However, if it becomes apparent that there is a preferred way, we should start listing that. 
- I also think it would be great to have a test repo on github with this setup and maybe a single module of code to start with, so that we can play with this new toy to understand what to do.

**Comment by jchiang87** [comment]
@rbiswas4 One can specify a configuration at the command line, e.g., 
```
pylint --rcfile=<file>
```

I'm not sure I understand what you want me to do regarding pushing to master but commenting out the pylint lines.   I guess I would suggest that everyone `futurize` their code and push to the `issue/209/python3_compatibility` branch.   Each push will trigger a travis build on that branch, which is fine, I think.  Once that branch builds cleanly, we can then merge into master.  

Regarding achieving 2-3 compatibility, I would say that if one's code is modified such that it passes the `pylint --py3k` test, it's good to go.   Note that with the `--py3k` flag, all other checks are disabled, so we may want to think about addressing other coding style issues separately.

What problems are you seeing regarding `numpy` modules?  If you have suggestions for an rcfile for pylint to suppress those, it might be worth checking such a config file into this branch.  We will probably need to iterate on what goes into that file.

**Comment by rbiswas4** [comment]
> On Apr 6, 2016, at 9:37 AM, James Chiang <notifications@github.com> wrote:
> 
> @rbiswas4 One can specify a configuration at the command line, e.g.,
> 
> pylint --rcfile=<file>
Ah good. So the rcfile can be supplied in the repository itself.
> I'm not sure I understand what you want me to do regarding pushing to master but commenting out the pylint lines. I guess I would suggest that everyone futurize their code and push to the issue/209/python3_compatibility branch. Each push will trigger a travis build on that branch, which is fine, I think. Once that branch builds cleanly, we can then merge into master.
> 

That sounds like a better alternative.
> Regarding achieving 2-3 compatibility, I would say that if one's code is modified such that it passes the pylint --py3k test, it's good to go. Note that with the --py3k flag, all other checks are disabled, so we may want to think about addressing other coding style issues separately.
> 
Sure
> What problems are you seeing regarding numpy modules? If you have suggestions for an rcfile for pylint to suppress those, it might be worth checking such a config file into this branch. We will probably need to iterate on what goes into that file.
> 
I will try to find an example.

**Comment by jchiang87** [comment]
@rbiswas4 BTW, I do have a little test repo that I've been using to experiment with the travis-ci configs.  Having one in DESC for people to try out and use as an example is a good idea.  I'll see about making one available.

**Comment by rbiswas4** [comment]
Incidentally, I did (hopefully correctly) fix whatever code I had put in. I also tried to insert absolute_import into other packages. 

- I am surprised by the travis comment on print being used. Python 2.7 already has the print function, so we can write a print command as 
```
print(printvalue)
```
but I still added the print_function import from __future__.

**Comment by jchiang87** [comment]
@rbiswas4 @jbkalmbach Since you guys are looking to do the same in Monitor, I should let you know that the [.travis.yml](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/issue/209/python3_compatibility/.travis.yml) file in the `issues/209/python3_compatibility` branch should be modified.  I added the `pip install future --upgrade` and `pip install pylint`  lines to the install section in order get a version of pylint consistent with what I have natively on my laptop.  I didn't think that update would have any adverse effects, but the older `future` module that comes with the recent conda dist of lsst-sims doesn't have a `builtins` module.   So if our code is modified with lines like
```
from builtins import range
```
so that it will pass the `pylint --py3k` test in travis, it won't be runnable under an out-of-the-box conda installation of lsst-sims.  I'll try to find time to fix things here in `Twinkles` later today.

**Comment by rbiswas4** [comment]
@jchiang87 
would it be good to try pymsql in place of MySQLdb for this purpose. Here is a page I stumbled on  with a comparison of available options: http://stackoverflow.com/questions/4960048/python-3-and-mysql

**Comment by jchiang87** [comment]
@rbiswas4 I've tried `pymysql` and it seems to work fine as a drop-in replacement for `MySQLdb` except for [a bug that I reported](https://github.com/PyMySQL/PyMySQL/issues/447).  Our NERSC db uses `port=3306`, so we are not directly affected, but it would be good if they fix the problem.  BTW, it seems that `astropy.time` also has a `MySQLdb` dependency (via `pytz`), so technically it also is not Python 3 compatible.

What are the DM team's plans for accessing MySQL tables under Python 3?

**Comment by rbiswas4** [comment]
It seems that the LSST DM team plans to use python_mysqlclient for this.

**Comment by jchiang87** [comment]
I've moved all of the db code to the `pserv` package.   Also, I've switched to using sqlalchemy similar to what is done in the sims code, so the code is never explicitly importing any mysql interface packages, i.e., the connection is made via code like [this](https://github.com/DarkEnergyScienceCollaboration/pserv/blob/master/python/desc/pserv/Pserv.py#L57).  Presumably a switch away from mysqldb would just involve changing the driver name to `+mysqlclient`?  In any case, I'm closing the issue here, since it's no longer directly relevant for Twinkles.   We can revisit in the pserv package.
