### ISSUE TITLE
Code Organization for Twinkles related projects

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#214]
We need to come up with a hierarchy of packages in order to prevent the situation where package A requires package B and package B requires some functionality in package A. Right now we have various LSST packages, OM10 . 

I think it is easy to simply say that these packages will never import Twinkles code (Twinkles code that is thought to be more generally useful will be pushed into these packages. ) The confusion for me arises with projects like Twinkles and Monitor (maybe others have a clear idea of what the intention was, I am just not sure). Is the idea that Twinkles will delegate certain issues to Monitor, so that Monitor is a dependency? Or will Monitor require utilities that are otherwise in Twinkles?

**Comment by jchiang87** [comment]
I think this is a good discussion to start having.  My preference would be to spin off functionality that is not Twinkles-specific into separate packages, e.g., postage stamp creation, db access, etc..  Since Monitor seems to be more generic than Twinkles, having Twinkles (and other packages) depend on Monitor seems fine to me, but stuff currently in Twinkles that is needed by Monitor should either be put in a totally separate package or moved to Monitor.

**Comment by drphilmarshall** [comment]
Sounds good. What are the principles we should try and stick to do when
building these sorts of inter-dependent packages? Should packages be
somehow "atomic" (ie small and indivisible), or is there a different
logical boundary to draw? I guess trying to keep each package as light
weight as possible is desirable too - but what trumps lightness?

**Comment by jchiang87** [comment]
The immediate problem we need to solve (or avoid) is circular dependency, e.g., Twinkles and Monitor somehow requiring the other.  More broadly, I think we'd like to avoid dependencies between packages that are nominally at the same level of generality, e.g., a WL package should not require functionality in Twinkles (the dependency tree shouldn't have any closed loops.)

I don't necessarily see a problem with a package providing a lot of different services, unless it becomes unwieldy to maintain, e.g., takes forever to build or has many versions being generated because there is a lot of development going on in different parts.  The main issue with lightness (i.e., a lot of small packages) may be package management and distribution.  We'd need to understand how to use eups for that.

**Comment by heather999** [comment]
In agreement with @jchiang87, I might add that it doesn't hurt to periodically review the packages to consider the need for refactoring and creation of smaller packages.

Speaking of eups.. I have been happy to see strides towards an improved eups introduction:
https://github.com/lsst-dm/dm_dev_guide/blob/master/build-ci/eups_tutorial.rst

**Comment by rbiswas4** [comment]
I suppose we can close this for now.
