### ISSUE TITLE
Sprinkling supernovae 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#26]
It seems that supernovae in catsim are still a ways off (right @SimonKrughoff ? #13) so how about we make a simple extension to the Sprinkler, so that it can make mock supernovae as well as mock lenses. These can be comically simple, its just placeholder code to allow @rbiswas4 to join in and think about how to include realistic simulated supernovae. Probably we should hear from both Simon and Rahul before getting too far down this road.

**Comment by drphilmarshall** [comment]
BTW @cpadavis and @digel are both ready to take this issue on, if a simple Sprinkler upgrade is all that is required in the first instance.

**Comment by rbiswas4** [comment]
@drphilmarshall The current status is in https://github.com/rbiswas4/SNIacatalogs. It would actually be very helpful if you would like to take a look at the current situation in the example demonstration (look at the section in the project README) either by running the ipython notebook or looking at the nbviewer page linked in the README. 

To summarize
- It produces instance catalogs of SNIa
- Distributions of SNIa model parameters are nominal, not tuned to data. My guess is that the most important one for you is the location of the SN wrt galaxy center. This is the task I want to address next.
- It is still an add-on rather than part of official catsim. I am working on trying to change my unit tests to not depend on the online database, once that is done I should be able to push.

**Comment by drphilmarshall** [comment]
Thanks Rahul, that's great! Looks like you are very close: when you say
"push" do you mean "push to catsim" or "push to SN1Acatalogs"? Our thought
was to get some SNe on teh sky quickly, and trust that whatever we did
could be refactored into the catsim level later: I coudl imagine reading
galaxy positions from an instance catalog, and then using your code to
sprinkle SNe on top of them.  Interested to hear what you and Simon think
of that interim approach: its what we did for the lenses (Sprinkle them on
top of catsim instance catalog galaxies). The question is whether we should
continue in interim mode, or just work on making catsim do what we want.

**Comment by rbiswas4** [comment]
push to catsim. SNIaCatalogs should work now (provided you have lsst sims packages and sncosmo as  the installation instructions detail) to produce instance catalogs of supernovae. It is a good time to know what columns will be needed in Twinkles or more generally if something is not as it should be.

**Comment by drphilmarshall** [comment]
Great! We hadn't realized catsim was so close to getting this important
upgrade!
What model do you use for assigning SNe to catsim galaxies? I guess you
have to get the SN class right, and then the position relative to the
galaxy.

**Comment by rbiswas4** [comment]
I may have given you some false hope. Right now I am only using the SALT model. I assign N (set to 1 right now, but can be say 5) supernova to each galaxy, but adjust their time of maximum so that the global SN rate is produced.

- I don't know how to assign SN classes to galaxies in a general way. I have a first guess which I used to have in place, but took out in order to tidy things up. This would change the probability of finding SN in galaxies depending on the stellar mass of galaxies. There are some correlations of SN properties like stretch and color with galaxy properties. I have never tried to add them, but I could whip up something if this is particularly important. To do this in a 'good way' is hard, because this may need to be built from correlations with observables rather than causal connections, and the observed correlations are likely biased because of selection effects. Thus, one needs to work out what true correlations would lead to observed correlations after figuring out selection effects. 

- The position wrt galaxy center has not been done either as I indicated in one of the previous comments here. My plan is to use sersic indices of galaxies to distribute the SN following the galaxy light but have not sat down to do this. Right now catsim galaxies only have easy sersics, but I would like to be able to do this more generally. If you have code to do this sort of thing, I would love to plug it in. Correct me if I am wrong, but my guess would be that this is the most important thing  (more than the previous issue) for twinkles, and for my own goals ... so this is the thing I would like to take up next.

**Comment by drphilmarshall** [comment]
I think it's enough to devise a _sufficiently plausible_ underlying model
for SN class given galaxy properties. Although perhaps for stress testing
of inference code we also want to make that _sufficiently complex_ so as to
give ourselves a hard time.

I guess the same goes for SN positioning: we need realism first, underlying
complexity second.

There could be people (currently) at SLAC interested in thinking about such
simulation schemes - let's see.

In general though, it sounds as though you are making good progress on
writing the "sprinkling" code directly into catsim, which is great!

**Comment by sethdigel** [comment]
Rather than start an e-mail thread I'll reveal my high-level ignorance here.  I have looked through Rahul's SNIacatalogs.  I have not used catsim in any serious way and have run phoSim only in a Hello World sense.  I may have some misconceptions on how things should work based on having worked on gamma-ray sky models for the Fermi data challenges.  I'd like to be sure that I understand at how things should work for the Twinkles simulations of SN Ia.  Here are some questions I'm looking for answers to.
* Can the input sources for phoSim be time dependent?  I'd assume yes, and that phoSim has an idea of absolute time.  On the other hand, the documentation for the phoSim Instance Catalogs seems to refer only to static sources
* Does a catsim output file (or whatever it is that is input to phoSim) have an associated time range of validity?  Is there a translation step needed between a catsim file (or set of tables) and an Instance Catalog for phoSim, e.g., for a specific time range and region of the sky?
* If the idea is that SN1acatalogs (or eventually catsim directly) defines SN1a sources to be added to the galaxies in a catsim file, how are the galaxies defined in the file?  By type, coordinates, orientation, Sersic index, distance, absolute magnitude,...?  
* Is there a catsim Variability model for SN Ia and does it have all the flexibility needed for this particular application?  How are SN Ia defined in catsim files?  Time, stretch parameter, distance, ...?  Are their positions defined absolutely or relative to the galaxy that they belong to?  How about their spectra and spectral evolution?  
* In SN1acatalogs (or eventually catsim) is the idea that it would randomly decide what SN Ia to place where and with what properties and when, based on some guidance regarding rates and an assumption about how their spatial distribution relates to the distribution of light in a galaxy?  And this would all be reproducible given a starting random number seed?

**Comment by rbiswas4** [comment]
> - Can the input sources for phoSim be time dependent? I'd assume yes, and that phoSim has an idea of absolute time. On the other hand, the documentation for the phoSim Instance Catalogs seems to refer only to static sources
- Does a catsim output file (or whatever it is that is input to phoSim) have an associated time range of validity? Is there a translation step needed between a catsim file (or set of tables) and an Instance Catalog for phoSim, e.g., for a specific time range and region of the sky?

Instance catalogs are catalogs pertaining to an 'instance of time' which I understand to be an exposure. As variability of our sources within exposure times is negligible, we simply need to supply these catalogs with sources at the appropriate time and position, whether the source is static or vairable.

> - If the idea is that SN1acatalogs (or eventually catsim directly) defines SN1a sources to be added to the galaxies in a catsim file, how are the galaxies defined in the file? By type, coordinates, orientation, Sersic index, distance, absolute magnitude,...?

They live on a database covering the coordinates of the sky. I might get the details wrong since I was not involved in building this (ask @SimonKrughoff for example), but as far as I know, the catalog contains redshift, coordinates, velocity, orientation, Sersic Indices (but with only indices 1 and 4), stellar masses of the bulge and disk. This is largely on the basis of simulations (one of the DeLuccia et al. papers) with SEDs assigned so that the color distribution reasonably matches those observed in SDSS.

I know there are efforts to improve this catalog, and personally, one of my major motivations for trying to link this catalog framework to SNe has been to be able to connect and build upon the considerable amount of work that has gone into and will go into building such catalogs.

> - Is there a catsim Variability model for SN Ia and does it have all the flexibility needed for this particular application?

I would say that it has quite a bit, though (perhaps as always) improvements are very much possible.

> -  How are SN Ia defined in catsim files? Time, stretch parameter, distance, ...?

SN are parametrized on the basis of a SALT2 model http://supernovae.in2p3.fr/salt/doku.php  (often the 'extended' version), which is a time series of spectra.  The parameters that decide on the SN properties are redshift, an amplitude 'x_0' , a parameter 'x_1' related to what is often called stretch parameter, a parameter called 'c' which is necessary to parametrize the  spectral slope. This is currently one of the widely used models in SN cosmology. The implementation is via sncosmo (http://sncosmo.readthedocs.org/en/v1.0.x/) which is now an external package used by catsim. 

 > - Are their positions defined absolutely or relative to the galaxy that they belong to? 
There is a vector providing the displacement of the SN relative to the galaxy 'center'. This must be distributed, according to the distribution of stars as you point out in the comments later. As I have said previously though, the vector is currently set to zero. 

> -How about their spectra and spectral evolution?
The spectra of the SN are from SALT2. There is no implementation of spectral evolution yet, ie. to say that SN properties and spectra are distributed independently of their redshift and host galaxy properties. 
We know this is not true in nature, but we lack the implementation currently. 


 > - In SN1acatalogs (or eventually catsim) is the idea that it would randomly decide what SN Ia to place where and with what properties and when, based on some guidance regarding rates and an assumption about how their spatial distribution relates to the distribution of light in a galaxy?

Yes. That is the hope. 
>  -And this would all be reproducible given a starting random number seed?
Actually, we are using a unique integer identifier of the galaxy which is already part of the database as a random seed. So, we don't have a single seed but as many as galaxies. But it is all reproducible given the same galaxies. If you change the galaxy realization (catalog) then things will be different.

**Comment by wmwv** [comment]
Rahul:

To perhaps more directly phrase:

How should we plan on/think about tracking time and phase of a SNeIa in phoSim+catSim?

Reading phoSim and catSim documentation will not leave you with the impression that there is an obvious way to do this.

Are we tracking Time of Explosion as one of the parameters?

 - Michael

**Comment by rbiswas4** [comment]
@wmwv 

> Are we tracking Time of Explosion as one of the parameters?

Sorry, when I listed the parameters of a SN, I should have included 't0' the time of peak in a particular band as defined by the SALT model. I forgot and only corrected it once I saw your message. 

So, the SN in the catalog know when their time of max light is. The InstanceCatalogs in the catsim framework know what the time of observation is (along with stuff like which bandpass is being used)  through obs_metadata objects . When instance catalogs are written out, this information is used and for SN, it is combined with the stored 't0' values to find the appropriate SED of the SN. 

Please let me know if this is not connecting to what you have thought. I have not really read much of the documentation, as I had the advantage of talking to people about it. I suppose reading that would help being on the same page.

**Comment by wmwv** [comment]
Hi Rahul,

Thanks for the clarification.  Your work on this has been key and most helpful, and I agree with your implementation and the description makes sense.

My point about the documentation was that the documentation not really helpful in explaining how to do this.  Thus, there is more of a burden on this project to explain very clearly what it's doing to help others understand how it works (partially because they may have not understood it to be possible).
 
- Michael

**Comment by drphilmarshall** [comment]
Definitely closed via #13
