### ISSUE TITLE
Point `_parent` link on NESRC data repo to correct input data repo.

### ISSUE THREAD

**Issue by wmwv** [DarkEnergyScienceCollaboration/Twinkles#263]
@tony-johnson 

Could you update 

```
/global/cscratch1/sd/tony_j/Twinkles/501
```

so that the `_parent` link points to the input data repo.  It currently points to

```
_parent -> /gpfs/slac/kipac/fs1/g/desc/work/501/input
```

This breaks assumptions the DM stack Butler makes that the parent data repository will be accessible from the output data repository.

**Comment by tony-johnson** [comment]
This happens when we copy output files from SLAC. The symlink should point to the directory used for reading the phosim input. That directory has not so far been copied to NERSC, but contains:

_mapper   (file used by DM)
registry.sqlite (file used by DM)
eimage (directory structure containing links to the actual phosim output)
raw (directory structure containing links to the actual phosim output)

A question for @jchiang87 -- is it sufficient to copy just the registry.sqlite to NERSC and change the _parent link to point to the directory containing that file?

**Comment by jchiang87** [comment]
You need the _mapper file too, but that's all.

**Comment by tony-johnson** [comment]
Instead of using these files I would now recommend using the "Run 2" output (see #201). The output is here:

/global/cscratch1/sd/tony_j/Twinkles/output/work/2/output

Since this was generated at NERSC all the symlinks should work, and this should (modulo unexpected NERSC/SLAC differences) be the same as  the earlier "Run 1.1" output.
