### ISSUE TITLE
Is there a newer version of Run1CPUTimes.ipynb

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#281]
@sethdigel I was trying to get a list of obsHistIds  of failed phosim runs for the light curve analysis, and was using the csv file mentioned in Run1CPUTime.ipynb. However this seems to be out of sync with the obsHistID values I am checking. For example, it seems obsHistID 230 shows up in the light curves, but in the phosim failures (runlimit==1) of the csv file. Should I be using a newer version of that file?

**Comment by sethdigel** [comment]
Ah.  Yes, that iPython notebook and the csv file date to the Hack day after the spring DESC meeting, at which time that particular visit had not finished (I think because the host running it had a problem).  I am just realizing that the pull request I made in May to merge in CPU time predictor code, and a complete metadata, file is still outstanding.  Jim had pointed out some pylint warnings that I missed at the time. I'll get on that.  In the issue/186/... branch the file is in the data directory.  Here's a link.

https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/issue/186/cpu_time_predictor/data/run1_metadata_v6.csv

**Comment by rbiswas4** [comment]
Thanks! @sethdigel
