### ISSUE TITLE
Run 3 Schedule

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#301]
Dear CI group Twinkles operatives, @richardxdubois cc: @tony-johnson @jchiang87 @TomGlanzman @heather999 @brianv0 @danielsf @SimonKrughoff 

Can you suggest a rough schedule for when you could support the main Twinkles 1 data generation run (Run 3), please? We're talking 12000 visits, PhoSim followed by DM Level 2. If you can let us all know your available windows, then the science team of @rbiswas4 @jbkalmbach @wmwv @cdfassnacht and I can get our instance catalogs and analysis capabilities ready in time. We know you'll be busy with DC1 PhoSim Deep as well as supporting other DESC projects too. Thanks!

**Comment by jchiang87** [comment]
Run3 is actually closer to 25,000 visits.  Discussing this during today's meeting, we decided that it would take at least a few weeks to do the phosim runs, so we decided on a deadline of Sept 9 for the instance catalog availability.  However, we also decided it would be better to generate the instance catalogs as part of the pipeline processing, i.e., run catsim at slac for each phosim run.  For this, we'll need @rbiswas4 to checkin the scripts he ran at NCSA for Run1.1.   Also that code will need to be updated to account for interface changes in the Stack since then.  We also need to finalize the sims distribution to use.  I'll make issues for these items so we can track the work.
