### ISSUE TITLE
Match Sprinkled AGN on magnitude

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#309]
Currently only matching source AGN on redshift. Need to add a requirement on magnitude as well.

**Comment by drphilmarshall** [comment]
i-band mean AB magnitude to be exact (which OM10 is not).

**Comment by jbkalmbach** [comment]
Hi @drphilmarshall, the columns in OM10 I'm wondering about are:

- MAGI_IN
- MAGI
- MAG (From previous discussion I know this is magnification, but just want to verify)
- ABMAG_I (I figure this is absolute and the one below is apparent, but magnitude of what?)
- APMAG_I

**Comment by drphilmarshall** [comment]
Apologies for the nightmarish naming scheme - they were not my choices!

- MAGI_IN = source plane (ie unlensed, intrinsic) i-band AGN mean magnitude
- MAGI = i-band magnitude of 3rd brightest (in a quad) or 2nd brightest (in a double) AGN image
- MAG - magnification factors for each AGN image (ie MAGI = MAGI_IN - 2.5*log10(MAG[k]) where k is in the index of the 3rd (or 2nd) brightest image)
- ABMAG_I = Estimated absolute magnitude of the lens galaxy, in the (rest-frame) i-band
- APMAG_I = Estimated i-band apparent magnitude of the lens galaxy
- VELDISP = velocity dispersion of the lens galaxy, in km/s

I do not trust the ABMAG_I and APMAG_I: better to find a massive CatSim galaxy that has (approximately) the same redshift and velocity dispersion, and use that.

**Comment by jbkalmbach** [comment]
Ok, so what I have put in place now after learning this is:
1) MAGI_IN values appear to be apparent magnitudes not the AB Mags you mentioned matching to above so I will match using apparent agn magnitudes as well.
2) Convert all om10 MAGI_IN values from i-band to imsimband to get mag_norm values.
3) Match sprinkled objects according to redshift +/- 0.05 and now additionally match agn_magnorm values to converted MAGI_IN values +/- 0.25 (what should this be?)

And then the final step will be adjusting the density parameter to account for the new matching requirements once we decide on a matching range for magnitude.

What do you think @danielsf @rbiswas4 @drphilmarshall?

**Comment by jbkalmbach** [comment]
Code visible in branch: https://github.com/DarkEnergyScienceCollaboration/Twinkles/tree/issue/309/match_sprinkled_agn_on_magnitude

**Comment by rbiswas4** [comment]
@jbkalmbach 

Is the reason that you prefer matching in mag rather than velocity dispersion because you don't have velocity dispersion on the catsim galaxies? From a different thread, I think @drphilmarshall explained that velocity dispersion should be a proxy for stellar mass, but I suppose you cannot do it without the exact mapping. Would it be easy to do it fi someone provided you a function 
```
def mass_stellar(vel_disp):
     ....
```
or would that still be harder than matching the i band magnitudes?

**Comment by jbkalmbach** [comment]
This issue is for the AGNs. I think we are planning on using some sort of mapping between vel. disp. and mass for the lens galaxies.

**Comment by rbiswas4** [comment]
Ah ok! So that is still the plan.

**Comment by drphilmarshall** [comment]
Your plan as written sounds good, Bryce. Just as point of information, "AB"
magnitudes are apparent mags in the AB system (ie relative to a flat
spectrum of standard normalization in Jy). An absolute magnitude can also
be given in the  AB system and are the apparent magnitudes that you would
measure if you were magically lucky/unlucky enough to be just 10pc away. I
was confused between AB and absolute for months when I switched to doing
optical astronomy. It is also by no means the only confusing thing, I found
:-)

PS. I think 0.25 mags slop in matching the AGN mags sounds sensible.

**Comment by jbkalmbach** [comment]
The 0.25 mags slop parameter gives us 132 lensed AGN systems when the density parameter is set at 1.0 in the sprinkler. Do we want to increase this leniency in magnitude to get more systems or are we happy with that number?

**Comment by drphilmarshall** [comment]
It'd be good to get to 400, to match the number expected from TDC1 (and to
give us a good chance of getting ~100 well measured time delays). Let us
know what it takes!

**Comment by jbkalmbach** [comment]
Expanding the magnitude bound to +/- 1.5 and the redshift to +/- .1 gives 352, how's that?

**Comment by drphilmarshall** [comment]
Hmm - that's pretty loose in magnitude, they need to be bright enough to
see! Can you try widening in redshift at fixed 0.25 mag spread please?
Sorry, should have thought of this earlier.

**Comment by jbkalmbach** [comment]
Ok, with a fixed .25 mag spread I did a few runs with different redshift spread.

|Redshift Spread| # Systems |
| ------------- | ------------- |
| .5 | 264  |
| .75  | 307  |
| 1.0  | 353  |

Let me know where you think the best tradeoff occurs and we'll set that up.

**Comment by drphilmarshall** [comment]
Even 0.5 is making me nervous. Can you try searching in a percentage range
rather than an absolute one, please? I worry that zs = [2.5:3:5] is
probably OK (as in the corresponding change in image separation and time
delay is not large) but zs = [0.5 : 1.5] is not, because the image
separations will come out wrong. I'd like to see what 10%, 25%, 50% ranges
get us.  Actually, since the 0.25 mag range is 0.1 dex, or about 30% in
flux, you could try searching in uniform ranges (0.1, 0.2, 0.25, 0.3) in
`log10(z)` in the same way. Thanks!

BTW this procedure will lead to simulated systems where the source redshift
does not match the observed image separation and time delay: it'll be as if
the lens galaxies have unexpected scatter in their masses, and they may end
up looking systematically different from a population of singular
isothermal ellipsoids. While this is not a problem for Twinkles 1, where we
are only interested in the deblending of images and extraction of light
curve and measurement of time delay, it would be a problem if we tried to
do those things using a hierarchical model for the populations of lenses
and sources - so we must aim to do better in Twinkles 2.

**Comment by jbkalmbach** [comment]
Results with magnitude difference fixed at .25:

|Redshift Difference (dex)| # Systems |
| ------------- | ------------- |
| .1 | 199 |
| .2  | 260  |
| .25  | 281  |
| .3 | 306 |

**Comment by drphilmarshall** [comment]
Let's go with 0.1 dex in both zs and flux then (=0.25 in magnitude). A sample of 200 lenses should make for a good analysis. Thanks Bryce! :-)

**Comment by jbkalmbach** [comment]
With merging of #336 we can close this.
