### ISSUE TITLE
Prepend instance catalog generation to phosim pipeline task

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#313]
Since we plan to generate the instance catalogs as a "pre-burner" to each phosim run, we need to modify the phosim pipeline to include that step.

**Comment by TomGlanzman** [comment]
This is basically done but for one (hopefully final) problem.  

Request: a modification to generatePhosimInputs.py so that the "--seddir" string is NOT prepended to the file path stored in the instance catalog for each object, but continues to be used as the location in which to store the generated data products.

Reason:

The generatePhosimInputs.py script takes an option to specify the directory in which to store the SED files ("--seddir").  However, the script then prepends that directory + "spectra_files/" to each object's filename in the instance catalog.  By intention, I specify "--seddir" as an absolute path in a special semi-persistent store for pipeline efficiency.  When I run the script in the pipeline, objects in the instance catalog then have SED references that look like: /long-path/spectra_files/...

When phoSim runs, specifying the "--sed" option causes that string to be prepended to the object's SED reference in the instance catalog.  In the pipeline task, this is specified as an absolute path, e.g., /another-long-path.  The production SEDs have relative paths in the instance catalog, e.g., starSED/..., so this makes sense.  For the custom generated objects, that same treatment results in a bogus path, /another-long-path//long-path/spectra_files/...

**Comment by jchiang87** [comment]
@TomGlanzman Can you make your request a separate issue and assign @rbiswas4 please?

**Comment by TomGlanzman** [comment]
Done.  Issue #351
