### ISSUE TITLE
Can we list a set of issues that lead to phosim crashes/long times?

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#314]
- [ ] Are there a list of issues that cause phosim crashes? We could check for those issues in the instance catalogs and issue a flag/warning that these conditions are satisfied (in which case the pipeline script can skip phosim generation and send us the obsHistID for investigation followed by separate generation
- [ ] Similarly if we can use Seth's predictor to quess  which runs would go over queue time, we could treat them differently

**Comment by TomGlanzman** [comment]
To the first point:  My experience with the first phosim run is that once a stable configuration is achieved, phosim runs very reliably.  There were no crashes/core dumps during the first Twinkles run that were code related.  In recent experience, I have only seen non-code related failures, such as I/O issues, running out of time, or inability of phoSim to fork() a new subprocess due to the host having exhausted its memory and swap space.  Others may have different experiences.

To the second point: Some combination of Seth's predictor algorithm and/or checkpointing should, in principle, solve this problem.  The latter would ideally be the only functionality needed.

**Comment by rbiswas4** [comment]
Let us leave the second point to the issue you started elsewhere ... I think we all agree that this would be a fruitful direction, and we have to figure out the details.

For the first point: I know for example bugs in the instance cataglog genertonthat can trigger a phosim crash
-  spectra should not have negative/ nan values (but 0 everywhere is OK?)
-  every record in the instance catalog should have a spectra associated with it
-  magnorm should not be nan

I am trying to get as long a list of such potential bugs that you might recall from your experiences with phosim into so that (a) we have tests to check for these and (b) the generation script validates that the instance catalogs are 'good for phosim' before submitting the resource intensive but unsuccessful phosim  jobs.

**Comment by TomGlanzman** [comment]
I have a couple of open bitBucket issues.  One, that phoSim crashes for (at least some) gzipped instanceCatalogs is easily worked around.  The other, that the centroid file appears corrupted when using internal checkpointing does need to be addressed -- but this does not cause a crash.

https://bitbucket.org/phosim/phosim_release/issues/11/problem-with-phosim-crash-when-using
https://bitbucket.org/phosim/phosim_release/issues/6/problem-interpreting-gzipped-instance

**Comment by rbiswas4** [comment]
Ok, those are important but those are not potential bugs of the instance catalog generation process that we can write unit tests to guard agains or validate instance catalogs with before submitting phosim jobs.

**Comment by drphilmarshall** [comment]
Should we conclude from the above discussion that there are no additional tests that need to be written?

**Comment by TomGlanzman** [comment]
These issues need to be enumerated in the Twinkles phoSim write-up.
