### ISSUE TITLE
PhoSim instance catalogs: speed up galaxies with pre-cooked FatBoy output

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#346]
@danielsf You and @rbiswas4 had this good idea, of speeding up the PhoSim instance catalog generation by not asking FatBoy to repeatedly go find the Twinkles galaxies every visit. Here's an issue to track your work on implementing this! :-)

@cwwalter We noted in the Twinkles meeting that this approach should also speed up the instance catalog generation for DC1 PhoSim deep as well, which is cool. We are finding that each IC generation takes about 20 mins right now, which is a significant (if not dominant) expense.

**Comment by rbiswas4** [comment]
> by not asking FatBoy to repeatedly go find the Twinkles galaxies every visit.
Actually the idea is not to talk to fatboy at all. 

Also @danielsf, if you do go on to think about doing tiling on the user side, do let me know, I probably have most of that code before I decided to do other stuff first.

**Comment by danielsf** [comment]
I am almost ready to submit a pull request addressing this issue.

The cache of Twinkles galaxies comes out to about 80 MB as a text file.  Are we okay just making that  a part of the repo, or should I try to do something clever with our setup scripts so that users generate the galaxy cache whenever they install Twinkles?

**Comment by jchiang87** [comment]
Can you add a script to generate the file so that the users have the option do it themselves?  And if it doesn't exist, can you have the code access fatboy in the usual way?  If that's a lot of work, then I'd say just commit the file.

**Comment by danielsf** [comment]
How about: if the file does not exist, I will call the code to generate it?  That should be pretty straightforward.

**Comment by jchiang87** [comment]
ok, sounds good to me.

**Comment by rbiswas4** [comment]
Slightly unrelated (since the suggested solution works well for the present case). We have and will be facing a more generic version of this problem often. Our examples and integration tests will depend on input files that are at least as large if not larger (1GB +) once we start adding in DM analysis.  This will likely hit us during hack week. Should we plan to allocate some data space on a web server?
