### ISSUE TITLE
Ordering obsHistIDs For Twinkles 3

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#347]
At the weekly meeting today we discussed a plan for ordering the obsHistIDs. The rationale behind this plan is that Twinkles 3 has ~ 25000 visits, which will probably take an appreciable amount of time, and we would like to be able to run meaningful analyses at intermediate times. So, the idea is to order the obshistids such that at intermediate times much shorter than the total walltime, we obtain sets of images which enable some analyses (in supernova and strong lensing analyses).  So the factors for ordering are
- Science analyses requiredments from SN and SL (SL has a preference for WFD, SN has a preference for complete light curves)
- PhoSim run times estimated via @sethdigel 's phosim time predictor: the idea being that we will try out the quicker runs first in the normal queues and think about other runs later, as our technology improves. 

This is the order that we provisionally agreed on:
- Drop duplicates: choose propid for WFD when duplicates exist
- We will select every unique band and night combination for run 3.1 and order them by expMJD first and then band. 
- In the case of multiple visits satisfying this combination of unique night + band:
   we select a WFD visit if possible, unless the phosim run time estimate exceeds a threshold T1
   If no WFD visit is selected select DDF visit with lowest phosim runtime.

My proposed choice of T1 is 120 Hours. Comments welcome!

**Comment by rbiswas4** [comment]
@sethdigel pointed us to 
```

Seth Digel [1:15 PM]  
@rbiswas4 , phosim_cpu_pred.py in the Twinkles repository will provide an estimated phosim CPU time for a given obsHistID; it is set up to use the kraken_1042 sqlite database.
```
on slack .

**Comment by sethdigel** [comment]
> Drop duplicates: choose propid for WFD when duplicates exist

What does this mean?  Duplicate combinations of pointing direction + filter but at different times, right?  Can a single observation be credited to more than one proposal?

Because for Twinkles Run 3 (3.1?) we are simulating the fields with no bright stars, the CPU time will be driven primarily by the altitude and phase of the moon.  Phil mentioned recently that we might consider the bright Moon times as effectively representing bad weather that leaves gaps in the time series.  I think that makes sense if we are not under sampling the OpSim visits for these fields anyway, and if we don't mind that the 'bad weather' will be periodic.  (Measurements of the cloud cover at Cerro Pachon indicate that 'on average more than 75% of the nights...are usable for observations', according to [this poster](https://www.lsst.org/sites/default/files/docs/Claver_086.18.pdf) by Claver et al.)

I suspect that once the pipeline really gets going, we will not need to worry a lot about the order of the simulations.  In principle the throughput could be a few thousand visits per day (at least for favorable moon altitudes).

**Comment by rbiswas4** [comment]
> Drop duplicates: choose propid for WFD when duplicates exist
What does this mean? Duplicate combinations of pointing direction + filter but at different times, right? Can a single observation be credited to more than one proposal?

Yes, in the current opsim implementation, a single observation can be credited to multiple proposals.
Since it is the same observation it will be at the same time, and the only difference in the two records is the `propID`. 

Therefore, in this selection what we always do in the first step is to drop one of those records. The only thing new is that we are being strict about which of those records to drop ie. we will drop the one with the DDF propid record (56).

So, the bad weather question is different right, and has to do with the dropped runs? I think the 'bad weather' is more like missing observations, but yes the statistical distribution would be more periodic than actual bad weather. Given that in SN, we are not really trying out cosmology so much, I am not worried about that too much. And we do not have much of a choice other than varying the threshold T1. Do you guys have a better feel for what would be nice to use as T1 ?

**Comment by sethdigel** [comment]
Yes, the bad weather question is different.  If we do not change the altitude of the moon from the OpSim values we will have visits that we cannot complete in the 120 CPU-hour limit on the SLAC batch farm.  Since we are not otherwise allowing for bad weather, this would sort of be making a virtue out of a necessity.  For Twinkles Run 1 about 10% of the visits never finished.  On the other hand, if you remember the plot below, it is clear that the 'bad weather' preferentially affected g, r, and i band observations.  So aside from the periodicity of the impact of the moon, this is another reason why we should not consider the lost observations 'bad weather'
![cpu_moonalt_comb](https://cloud.githubusercontent.com/assets/6035835/19615267/8cb5f7c6-97b1-11e6-9392-55e6e4ea66b8.png)
(I noticed today that part of the reason the CPU time depends so steeply on whether the moon is above the horizon is that if moonalt < 0, phosim sets its magnitude to 10000.)

The CPU time predictor is estimating the time required to run the visit on a 'fell' class CPU in the batch farm.  These are fairly common but now also relatively slow hosts.  (I have a table of relative speeds on [this](https://confluence.slac.stanford.edu/display/LSSTDESC/Phosim+CPU+times+in+Twinkles+Run+1+and+Run+1sx) Confluence page.  So if a visit will run in 120 CPU hours on a fell host, it will probably run on any of the hosts.  Still, there's a down side to guessing wrong (using 5 CPU days with nothing to show for it), so I'd recommend being a little conservative and going with T1 = 100*3600 CPU seconds.
