### ISSUE TITLE
Embed lenses into catalogs

### ISSUE THREAD

**Issue by connolly** [DarkEnergyScienceCollaboration/Twinkles#37]
Integrate OM10 sources within the catalog framework tying to the galaxy source populations (i.e. the appropriate redshifts)
- [x] find the appropriate galaxy (redshift appropriate for OM10 lens)
- [x] replace galaxy with lens galaxy
- [x] assign proper SED to lens galaxy #45
- [x] select the density of lensed galaxies
- [x] assign lens times in a self consistent fashion (as in the SNe generation)
- [x] add in time delay to lens images of same object
- [x] translate OM10 magnitude normalization to catsim magnitude normalization

**Comment by wmwv** [comment]
Why are we merging issues into one?  I would have thought there would be strength and clarity in keeping issues separate.  The comment and discussion would be different and separately maintained on each issue.

I think it's fine to have a tracking issues with a check list that gets boxes checked off when other issues are closed.  But it's confusing to merge otherwise separable activities.

**Comment by connolly** [comment]
We discussed this in the context of zenhub and trying to group tasks into coherent packages of work. When tasks/issues are grouped together (e.g. as epics in the JIRA agile world) it is easier to follow their progress (as opposed to having them spread around as a series of many subtasks). If zenhub had the concept of epics this would not be an issue (I think they are working on it) but this was an attempt to see how we could replicate the concept of an epic without having epics.

We can break out the subtasks - it will increase the number of issues by a factor of 5. I guess could try to accomplish the epic concept with labels to link the tasks together.

**Comment by jbkalmbach** [comment]
So, in the interest of sparing people's inboxes, I would like everything to be explicit here before I do any more opening and closing of issues. 

The idea is for each item on this checklist to be a separate issue and when they get closed we will check them off here. Furthermore, in order to keep track of them as stories that belong to a single epic, I should use the name of this issue (the "epic" issue we can call it) as a label that they all are assigned?

**Comment by drphilmarshall** [comment]
That sounds like a good plan, @jbkalmbach !

**Comment by jbkalmbach** [comment]
We have lenses in Instance catalogs. All tasks completed.

**Comment by drphilmarshall** [comment]
EPIC
