### ISSUE TITLE
Update Strong Lensing information with minion_1016

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#378]
The ids given for clashes with SNe were based upon a run from kraken_1042 and the numbers of SL systems are also from this. We need to run with minion_1016 to see if these change and update accordingly.

**Comment by jbkalmbach** [comment]
It seems we're okay here. I made a [notebook](https://gist.github.com/jbkalmbach/00d5b72f08329b27f1506b7ef0db07c9) that verifies the results. The lens galaxy ids are the same as before.

**Comment by drphilmarshall** [comment]
Great! Thanks for checking - this could have been annoying.

**Comment by jbkalmbach** [comment]
@rbiswas4 Are you satisfied that this isn't a problem and can I close this?

**Comment by rbiswas4** [comment]
Am I right in understanding that this is a catalog of a spherical patch? So, the OpSim database characteristics are not important at all. 

The only worry that we had discussed was the ordering of the ids from the database query. Is that handled by doing an order by somewhere ?

**Comment by jbkalmbach** [comment]
I think you are talking about what I proposed in #379, right?

**Comment by rbiswas4** [comment]
I see that is a different issue!

I certainly don't disagree with your claim that this is resolved. But then, I am just unsure that I understand what might have gone wrong (I guess the reason you were worried), probably because I missed the discussion. This would have seemed to be independent of OpSim, since all you are using from OpSim are uncertainty properties. So were you worried about some kind of uncertainty threshold or something else that I am completely missing?

**Comment by jbkalmbach** [comment]
Yeah, I guess I didn't really expect anything to change, but wanted to erase any doubt.
