### ISSUE TITLE
Utility for examining diffims

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#396]
Requirements:
specify visit on command line.
list possible diffims
Overlay masks
overlay dia sources -- red plus
overlay direct sources -- green circle
Display:
 Frame 0: Direct
 Frame 1: diff
 Frame 2: diff - direct

**Comment by rbiswas4** [comment]
Somethings that we may want to do by adding to this:
- Can we later access the template and Direct (I am assuming this is the science image)  at different stages of processing? I am guessing that the default will be the template and science images transformed by (preconvolution, warping, and kernel matching) so that a direct pixel by pixel subtraction gives the resultant difference image?
- Can we change the threshold of detection?
- Can we look at the difference image around a ra, dec value?

**Comment by SimonKrughoff** [comment]
> Can we later access the template and Direct (I am assuming this is the science image) at different stages of processing? I am guessing that the default will be the template and science images transformed by (preconvolution, warping, and kernel matching) so that a direct pixel by pixel subtraction gives the resultant difference image?

There are a couple of pre-defined data products that will help with this, but mostly this will require turning on the debugging output and running in the interactive debug mode.

> Can we change the threshold of detection?

Not interactively in a tool like this.  We would have to rerun the data to get this.

> Can we look at the difference image around a ra, dec value?

You mean other than using the built in utilities in DS9?  We could do this, but it seems like just using the display tools is the way to do this rather than building an ad hoc cutout service.

**Comment by rbiswas4** [comment]
> Can we change the threshold of detection?
Not interactively in a tool like this. We would have to rerun the data to get this.

More clearly, I meant that after running the diffim, can I find out unique locations of a residual which have different levels of significance than the default. If that requires re-running, I  am guessing that you mean re-running the difference image task rather than the previous image based steps.

**Comment by SimonKrughoff** [comment]
> More clearly, I meant that after running the diffim, can I find out unique locations of a residual which have different levels of significance than the default. If that requires re-running, I am guessing that you mean re-running the difference image task rather than the previous image based steps.

Correct.  There is no way to change the detection threshold interactively.  The diffim step needs to be rerun with another threshold.  There has been talk of allowing multiple detection thresholds, but I don't know how that translates into the mask layer.

**Comment by rbiswas4** [comment]
Ok. But we can always run this looping through the diffim task at multiple thresholds if we really want to ...

**Comment by SimonKrughoff** [comment]
Merged as part of #397
