### ISSUE TITLE
Create a workflow engine to generate and process the twinkles data

### ISSUE THREAD

**Issue by connolly** [DarkEnergyScienceCollaboration/Twinkles#40]
Create an end-to-end simulation and data processing framework
- [ ] run the query on the catalogs?
- [ ] define the workflow input files to take the phosim catalogs and distribute across machines and gather the input data
- [ ] write the workflow code and execute test runs for generation
- [ ] configure workflow input files to run the DM processing on the resulting images

**Comment by drphilmarshall** [comment]
Looks like @tony-johnson @TomGlanzman @richardxdubois and @SimonKrughoff are making a start on this today at the ANL2015 meeting Hack Day. You could use this issue to present your product if you like!

**Comment by drphilmarshall** [comment]
Here's what the team produced at the Hack Day:

A workflow diagram:
![image](https://cloud.githubusercontent.com/assets/710903/11100530/a27b3ae0-8866-11e5-99db-a96bc350f95a.png)

A stack-processed image:
![image](https://cloud.githubusercontent.com/assets/710903/11100548/be21e960-8866-11e5-864e-943d0140f309.png)

Look at those lovely catalog objects! :-)

@tony-johnson @TomGlanzman @richardxdubois : can you please check in the code that you wrote to do this, please? @SimonKrughoff has a cookbook ( in #41 ) of chained DM pipeline tasks that could also be run with the workflow engine you used to make this image. I'd like to reproduce both his and your results on my laptop, so I need both the scripts to call, and also the engine with which to call them. Thanks!

**Comment by SimonKrughoff** [comment]
@drphilmarshall [here](https://lsst-web.ncsa.illinois.edu/~krughoff/data/twinkles_first_9.tar.gz) are the data I used to create my cookbook, so you should be able to use them to reproduce what I've done.  Once you have gotten through processCcd you follow the following recipe to get an image like the one above.  

Note that you will have to do `$> setup display_ds9` before you start.  You'll also need ds9 on your PATH.  Start an interactive python environment and then:
```
>>> import lsst.daf.persistence as daf_persist
>>> import lsst.afw.display as afw_display
>>> butler = daf_persist.Butler('output_data')
>>> dataId = {'visit':840, 'sensor':'1,1', 'raft':'2,2', 'filter':'r'}
>>> calexp = butler.get('calexp', dataId=dataId)
>>> src = butler.get('src', dataId=dataId)
>>> display = afw_display.getDisplay()
>>> display.mtv(calexp)
>>> display.setMaskTransparency(70)
>>> for x, y in zip(src.getX(), src.getY()):
...     display.dot('o', x, y)
```

**Comment by drphilmarshall** [comment]
Alright! @TomGlanzman @tony-johnson @SimonKrughoff and I just hung out for an hour to discuss getting Simon's cookbook sequence turned into an XML format "workflow" for input into The Workflow Engine (I am learning the words, here). The idea is that each workflow will inhabit its own folder, which will contain 1) the xml file, 2) the markdown README that explains what this particular Workflow Engine "task" is doing, and then 3) whatever other scripts are needed to call the DM "tasks" (Simon's python files). Note the exciting overloading of the words "task" and "workflow"! 

Tom, can you please push your workflow folder with a minimal README and xml file s as soon you have created them, so that we can follow along as you commit your changes? This will allow you and Tony to discuss the design of the system in the open, so we can all learn how this is going to work as you build it :-)

While the xml file and scripts are what The Workflow Engine need in order to run, we talked a bit about how hacker scientists like me should try and keep up, doing experiments on very small scales in the hopes of making useful contributions to the DM task configurations etc. The conclusion was: as long as we follow a good set of standards for where the various data files (images, catalogs etc) live, we should be able to step through a given workflow executing DM scripts manually (as in Simon's cookbook). I daresay it will be easy to extract these from the xml file too. 

Tom, Tony: looking forward to seeing what you come up with! Others, feel free to ask questions, pass comment, cheer them on etc :-)

**Comment by drphilmarshall** [comment]
I think its fair to say that the workflow engine has now been "created" and is in ongoing development :-) @tony-johnson @TomGlanzman @SimonKrughoff @jchiang87 please start new issues, one per item on your to-do lists, so we can follow along. Thanks!
