### ISSUE TITLE
Environment set-up

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#59]
We're soon going to be running sims and DM code in multiple places. I suggest we adopt a common set-up script, that sets up the environment that Twinkles needs in each place our scripts are running. @jchiang87 maybe we can start with the setup script that you and others are using at SLAC? I'd suggest we call it `loadTwinkles.sh` or something, and keep it in a folder called `bin` or `setup` or something. 

Should this script check for the correct versions of things, so that we know we are running exactly the same DM and sims code?

**Comment by jchiang87** [comment]
Sure, I can check in that setup script and name it as you suggest, but making it a general purpose tool (as opposed to a SLAC-specific script) may be a bit challenging since it currently assumes om10 and specific branches of pipe_tasks and obs_lsstSim have been checked out and built by hand.   We're really delving into the package management (especially with regard to version checking) and build system domains (which are good things to sort out!), so a sufficiently general implementation may take a while to get together.

**Comment by drphilmarshall** [comment]
That's fine - it doesn't have to be too general purpose. In a way, it's the just the documentation a new user would need to get running at say NERSC or Fermilab - you need this package and then this one and etc. Thanks Jim!

**Comment by jchiang87** [comment]
I just checked in installation notes and a version of the loadTwinkles.bash setup script.
