### ISSUE TITLE
Large file

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#89]
I did kind of a bad thing and checked in a 10MB png.  Do we want to take care of that now by rewriting history and putting the file elsewhere or are we o.k. with a few large files lying around since this repo is likely to end up with lots of analysis type files (not just code)?

Another option is to turn it into a git-lfs repo, but that would also require rewriting history to get rid of binary files.  Thoughts?

**Comment by wmwv** [comment]
Keep for now.

As you allude to, turning this into a git-lfs repo doesn't solve this problem because step one would be re-writing history anyway.  It would only address future problems.  We can keep this in mind.  It would be my preference to wait a couple of more months for `git-lfs` to mature before requiring it to participate in Twinkles.

**Comment by SimonKrughoff** [comment]
Sounds good. Closing.
