### ISSUE TITLE
Commit physics override file for phosim runs for Twinkles Run 1

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#92]
This is related to issues #63, #73, and #91 .  @SimonKrughoff I think you are best suited to produce a candidate set of physics overrides.   Once we have consensus on what this should contain, Tom can proceed with #91 and eventually generating the full Run 1 dataset.

**Comment by johnrpeterson** [comment]
please assign this to me.  this should have input from the phosim team.

john

**Comment by jchiang87** [comment]
@johnrpeterson You would certainly have been part of the consensus on this, but if you want to take it on, great.   It would be good to have this today.  Please keep in mind Simon's comments at https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/63#issuecomment-163028874 .
We'll still all need to agree on the final version.

**Comment by SimonKrughoff** [comment]
I'll produce a suggested physics override file today.  I think @cwwalter may also have input on this since he has extensive experience with turning things on and off in phosim.

**Comment by drphilmarshall** [comment]
Thanks all. I expect there will need to be a bit of back as forth on this
before we each reach consensus: a good format for such exercises is google
docs.

Simon, would you mind making one, scribbling down a quick first attempt,
making it editable by everyone with the link, and then posting the URL to
this thread? (I don't think we are likely to get spammed while we do this).
The reason we should only make a rough first pass is to get John's input
ASAP - but he'll have a better idea of what were trying to do if he reads
Simon's list first. And of course we can all comment on the doc as it
evolves. Sound like a plan?

**Comment by johnrpeterson** [comment]
we probably should go with the following command file:

pixelerror 0
chargesharing 0
fieldanisotropy 0

**Comment by cwwalter** [comment]
Here is a link to a file which turns most effects off:

https://github.com/cwwalter/brighter-fatter/blob/master/command-files/perfect_seeing

There is also a clear everything command but it doesn't get quite everything and I'm not quite sure if it is in the release version you are using yet.

**Comment by SimonKrughoff** [comment]
@drphilmarshall I can take a first go.  In addition to @johnrpeterson 's suggestions I think we'll want to turn of clouds and set zenith_v to something reasonable.  I'll attach a link shortly.

**Comment by johnrpeterson** [comment]
why would you want to turn off clouds.  its the primary driver of photometric variability.

john

**Comment by SimonKrughoff** [comment]
@johnrpeterson regarding turning off clouds, there are two reasons.

First, I think there is benefit from starting with an ideal case.  That will allow us to find simple problems without confusing them with complicated systematics.
Second, I have not seen any validation/verification of the cloud model.  In my experience it is a bit heavy handed (i.e. I have never seen photometric conditions with clouds turned on).

**Comment by SimonKrughoff** [comment]
All, here is a first go at the physics override file.  My goal was to have realistic PSFs, but turn off all the things that ISR should take care of.  I have some question as to whether we should turn off saturation and bad pixels, so any input there would be useful.

We had talked about a physics override file per visit.  I don't think we can do that, but I do think we can have a physics override file per filter.  The only difference between the three would be the dark sky value. 

Here's the link.  Edit away:
https://docs.google.com/document/d/1IQGQMhQI8po5V1axtmjsxUfj6e2GOE2kVNBWseDxBY8/edit?usp=sharing

**Comment by johnrpeterson** [comment]
these should be changed for sure:

1) blooming, saturation, charge diffusion commands should be removed.
2) having a different value of zenith_v for each filter doesn’t make any sense.  if you are going to force it to be one value, then just pick one. 

these are highly unrealistic (most of the instrumental psf is removed and there will be little photometric variation) but if according Phil/Michael that is the philosophical approach of twinkles one it would be ok. so we need some guidance about the goals

3) removing clearperturbations, cleartracking, clearclouds, and zenith_v as one value
 

john

**Comment by drphilmarshall** [comment]
Thanks Simon. Let me try to extract te principle you are trying to follow,
to see if I understand it:

When making Twinkles 1 eimages to be processed into level 2 catalogs by the
DM stack, we should not simulate effects that would have been (purportedly)
removed by the stack at an earlier stage. This is the optimistic stack
approximation, where we assume that the low level Level 2 image processing
(ISR) software will work perfectly; it allows us to focus on the DM stack's
object detection and measurement performance.

**Comment by SimonKrughoff** [comment]
@drphilmarshall 
> When making Twinkles 1 eimages to be processed into level 2 catalogs by the
DM stack, we should not simulate effects that would have been (purportedly)
removed by the stack at an earlier stage. This is the optimistic stack
approximation, where we assume that the low level Level 2 image processing
(ISR) software will work perfectly; it allows us to focus on the DM stack's
object detection and measurement performance.

That is my intent.  I think it makes sense to do that now and then to expand to what happens when low level calibration goes wrong.

**Comment by SimonKrughoff** [comment]
@johnrpeterson 
> 1) blooming, saturation, charge diffusion commands should be removed.

If we leave them on, I agree.  I was trying to make it very obvious what I was turning off and what I was intentionally leaving on.

> 2) having a different value of zenith_v for each filter doesn’t make any sense.  if you are going to force it to be one value, then just pick one.

I think we have to have a sky value per band.  The typical dark sky brightness differs by ~2 mag between g and i.  Since the variation in the dark sky from literature is ~0.2 mag, I think we would be doing ourselves big disservice by just picking one number.

>these are highly unrealistic (most of the instrumental psf is removed and there will be little photometric variation) but if according Phil/Michael that is the philosophical approach of twinkles one it would be ok. so we need some guidance about the goals

Can you expand on this?  My intent was to leave the PSF alone.  That needs to be as right as possible.  I just wanted to simplify the second order things (tracking errors, etc.).  What have I got turned off that should be turned on?

> 3) removing clearperturbations, cleartracking, clearclouds, and zenith_v as one value

You are saying leave perturbations and tracking on?  What effects do these include?

I would like there to be no clouds in this run (for reasons I mentioned earlier).  That is done with the clearclouds command right?  Does anyone have a strong reason to leave clouds on?

**Comment by johnrpeterson** [comment]
> On Jan 12, 2016, at 2:40 PM, SimonKrughoff <notifications@github.com> wrote:
> 
> @johnrpeterson <https://github.com/johnrpeterson>
> 1) blooming, saturation, charge diffusion commands should be removed.
> 
> If we leave them on, I agree. I was trying to make it very obvious what I was turning off and what I was intentionally leaving on.
> 
this is still confusing because it is a subset.  please remove these. 
> 2) having a different value of zenith_v for each filter doesn’t make any sense. if you are going to force it to be one value, then just pick one.
> 
> I think we have to have a sky value per band. The typical dark sky brightness differs by ~2 mag between g and i. Since the variation in the dark sky from literature is ~0.2 mag, I think we would be doing ourselves big disservice by just picking one number.
> 
> 

it will be a different value in each band even if you pick one value.  it is not the brightness in the simulated band, it is the v-band brightness.  so that’s why you do one number.

> these are highly unrealistic (most of the instrumental psf is removed and there will be little photometric variation) but if according Phil/Michael that is the philosophical approach of twinkles one it would be ok. so we need some guidance about the goals
> 
> Can you expand on this? My intent was to leave the PSF alone. That needs to be as right as possible. I just wanted to simplify the second order things (tracking errors, etc.). What have I got turned off that should be turned on?
> 
> 3) removing clearperturbations, cleartracking, clearclouds, and zenith_v as one value
> 
> You are saying leave perturbations and tracking on? What effects do these include?
> 
perturbations is roughly half of the instrumental psf, so you’ll want to leave that on.  tracking is smaller but for the same reason that should remain on.

> I would like there to be no clouds in this run (for reasons I mentioned earlier). That is done with the clearclouds command right? Does anyone have a strong reason to leave clouds on?
> 
> 

there is always some cloud opacity in real life.  it may be rather small.  so don’t turn this off, because you want to make it more realistic.  it is more realistic if it is on, in fact.  you can turn it off if you want to simplify the photometry though.  that would be a legitimate reason.

**Comment by SimonKrughoff** [comment]
@johnrpeterson feel free to edit the document directly.

> this is still confusing because it is a subset.  please remove these.

I'm missing something.  What is it a subset of?  If we decide to turn off saturation, is that done with another command?

> it will be a different value in each band even if you pick one value.  it is not the brightness in the simulated band, it is the v-band brightness.  so that’s why you do one number.

Sorry about that.  Of course you are right.  I set it to 21.8.  That seems reasonable based on the Krisciunas et al. (2007) paper.

> perturbations is roughly half of the instrumental psf, so you’ll want to leave that on.  tracking is smaller but for the same reason that should remain on.

Done 

>there is always some cloud opacity in real life.  it may be rather small.  so don’t turn this off, because you want to make it more realistic.  it is more realistic if it is on, in fact.  you can turn it off if you want to simplify the photometry though.  that would be a legitimate reason.

Part of the reason for leaving clouds off is that, in my experience with phosim, there are significantly more clouds than I expected.  Is there any validation of the cloud model?  In the interest of keeping the configuration to something we understand, I'd like to keep clouds off unless we can verify that the model reflects the conditions we expect at Cerro Pachon.

**Comment by johnrpeterson** [comment]
so basically we now have the following.


these are the final commands to remove basically all physics related to non-uniform pixels which DM cannot fully handle at the moment.  these i wouldn’t argue with.

pixelerror 0
chargesharing 0
fieldanisotropy 0
fringing 0

then the only other two are:

zenith_v 21.8
clearclouds

both of these will simplify the photometry drastically because the background will not vary as much as real life and the throughput will be quasi-constant (although not exactly).  if, for simplicity, the scientific goals of the first twinkles run is to keep it simple then i would add them.  if that’s not the goal, don’t add them though.

john







> On Jan 12, 2016, at 3:30 PM, SimonKrughoff <notifications@github.com> wrote:
> 
> @johnrpeterson <https://github.com/johnrpeterson> feel free to edit the document directly.
> 
> this is still confusing because it is a subset. please remove these.
> 
> I'm missing something. What is it a subset of? If we decide to turn off saturation, is that done with another command?
> 
> it will be a different value in each band even if you pick one value. it is not the brightness in the simulated band, it is the v-band brightness. so that’s why you do one number.
> 
> Sorry about that. Of course you are right. I set it to 21.8. That seems reasonable based on the Krisciunas et al. (2007) paper.
> 
> perturbations is roughly half of the instrumental psf, so you’ll want to leave that on. tracking is smaller but for the same reason that should remain on.
> 
> Done
> 
> there is always some cloud opacity in real life. it may be rather small. so don’t turn this off, because you want to make it more realistic. it is more realistic if it is on, in fact. you can turn it off if you want to simplify the photometry though. that would be a legitimate reason.
> 
> Part of the reason for leaving clouds off is that, in my experience with phosim, there are significantly more clouds than I expected. Is there any validation of the cloud model? In the interest of keeping the configuration to something we understand, I'd like to keep clouds off unless we can verify that the model reflects the conditions we expect at Cerro Pachon.
> 
> 


yes, of course that has been studied.

**Comment by SimonKrughoff** [comment]
>> Part of the reason for leaving clouds off is that, in my experience with phosim, there are significantly more clouds than I expected. Is there any validation of the cloud model? In the interest of keeping the configuration to something we understand, I'd like to keep clouds off unless we can verify that the model reflects the conditions we expect at Cerro Pachon.

> yes, of course that has been studied.

@johnrpeterson can you please point me to some validation of the cloud model?  My experience with phosim is in contradiction with what I expect from the site.  I just want to make sure we aren't making things harder on ourselves than we need to at the beginning.

**Comment by SimonKrughoff** [comment]
I've converged on a [physics override](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/twinkles/twinkles_I_physics_override.txt) that seems reasonable to me.  I still have the Google doc open if people want to make suggestions, but I also checked in a text version.

@TomGlanzman will you give this file a try on your system just to make sure it doesn't raise any errors?

**Comment by TomGlanzman** [comment]
Thanks @SimonKrughoff , the first test job is running now...

Please let me know if the overrides change.

**Comment by drphilmarshall** [comment]
Marvellous!

Now, in order to have the best possible conversation at SLAC in March, I
think we want to make a few variations on this "easy baseline", for
comparison. What do you think? Is that too much of a logistical nightmare?
One easy way to do this could be to make each year of a three year campaign
use a different override file - and then look at our validations tests year
by year.

John, if we did this, which two variations would you suggest we try? One
that is identical except for having clouds turned on? And one that has the
default settings (ie maximal difficulty)?

I suggest this just because I think we learned in the last few weeks of
discussion is that a) we are still in the process of figuring out what will
be most useful for our DM stack tests, and b) that there are some useful
comparison tests to be done that the Twinkles images could maybe help with.
What do you all think?

**Comment by SimonKrughoff** [comment]
@drphilmarshall I wonder if it would be more informative to run the full Twinkles I with the "easy baseline" then rerun some subset of that with a more complex system: default values, with just clouds turned on, or something else.  Having the same input catalog run through in two different configurations may make it easier to track things down.  Just a thought.

**Comment by drphilmarshall** [comment]
Yes, that would allow object by object comparisons as well as statistical
ones across the whole catalog. But it seems like more work before March 7.
Let's do run 1 with just the one override file, and then about any
variants, then.

**Comment by wmwv** [comment]
@SimonKrughoff @drphilmarshall I very much agree that running a full Twinkles 1 with the "easy baseline" will be much more useful to have by March.

**Comment by johnrpeterson** [comment]
All-

you have to turn back on blooming and saturation.    bright stars will take way too long without it.  its fine to do for a single chip, but most likely its going to cause problems with a big data challenge.

john

**Comment by SimonKrughoff** [comment]
O.K.  We'll need a minimal ISR.  I've made an issue #94 for that.

**Comment by SimonKrughoff** [comment]
It seems like we've got something to work with, so I'm going to close this.

In an effort to keep track of things as they come up, I've created [PHOSIM-19](https://jira.lsstcorp.org/browse/PHOSIM-19) to track conversation on the cloud model.
